import type { Opportunity, DataSource } from "./types";

// ============================================================
// DATE REALE -- Agregate din surse verificate din Romania & UE
// Ultima actualizare: Mai 2026
// Surse: ANPCDEFP, suntsolidar.eu, SALTO-YOUTH, Innovation Labs,
//   Let's Do It Romania, Crucea Rosie, Habitat for Humanity,
//   Teach for Romania, BCR Scoala de Bani, World Vision, edu.ro,
//   Cantus Mundi, Ora de Net, Ajungem Mari, Young Initiative,
//   CONCORDIA, AGLT, Fundatia Calea Victoriei, Opera Comica,
//   Eurodesk Romania, United Way, olimpiade.ro
// ============================================================

export const mockOpportunities: Opportunity[] = [
  // == VOLUNTARIAT ==
  {
    id: "1",
    title: "Let's Do It, Romania! -- Ziua de Curatenie Nationala 2026",
    description:
      "Cea mai mare miscare sociala din Romania. Pe 19 septembrie, alatura-te sutelor de mii de voluntari care curata parcuri, paduri, maluri de rauri in toate cele 41 de judete. Inscrie-te pe platforma app.letsdoitromania.ro.",
    category: "voluntariat",
    organization: "Let's Do It, Romania!",
    location: "Toata Romania (41 judete)",
    date: "19 Septembrie 2026",
    ageRange: "14+ ani",
    tags: ["ecologie", "curatenie", "comunitate", "natura"],
    isFree: true,
    url: "https://letsdoitromania.ro/project/ziua-de-curatenie-nationala/",
    source: "letsdoitromania.ro",
    difficulty: "ușor",
    createdAt: "2026-03-19",
  },
  {
    id: "2",
    title: "Corpul European de Solidaritate -- International Countryside",
    description:
      "Proiect ESC de voluntariat international in mediul rural. Activitati de dezvoltare comunitara, agricultura sustenabila si schimb intercultural. Cazare, masa, transport si bani de buzunar -- totul acoperit de UE.",
    category: "voluntariat",
    organization: "Corpul European de Solidaritate / ANPCDEFP",
    location: "Romania (diverse localitati rurale)",
    date: "8-12 Iunie 2026",
    deadline: "15 Mai 2026",
    ageRange: "18-30 ani",
    tags: ["international", "europa", "rural", "sustenabilitate"],
    isFree: true,
    url: "https://www.suntsolidar.eu/evenimente-det/vrs/IDev/2605",
    source: "suntsolidar.eu",
    difficulty: "mediu",
    createdAt: "2026-04-01",
  },
  {
    id: "3",
    title: "Crucea Rosie Romana -- Devino Voluntar",
    description:
      "Alatura-te familiei de peste 6.000 de voluntari Crucea Rosie din Romania. Activitati in prim ajutor, sprijin pentru varstnici, actiuni in cazuri de dezastre naturale si proiecte comunitare. Formari gratuite oferite.",
    category: "voluntariat",
    organization: "Crucea Rosie Romana",
    location: "Toate filialele din Romania",
    date: "Program continuu -- inscrieri deschise",
    ageRange: "16+ ani",
    tags: ["sanatate", "prim ajutor", "umanitar", "comunitate"],
    isFree: true,
    url: "https://crucearosie.ro/implica-te/voluntariat/formularul-de-inscriere-pentru-voluntari/",
    source: "crucearosie.ro",
    difficulty: "ușor",
    createdAt: "2026-01-15",
  },
  {
    id: "4",
    title: "Teach for Romania -- Program de 2 Ani la Catedra",
    description:
      "Recrutare deschisa pentru generatia 2026. Devino profesor in scoli publice din 30 de judete, ajutand peste 38.000 de copii. Training complet oferit, sustinere pe toata durata programului. 336 de scoli partenere.",
    category: "voluntariat",
    organization: "Teach for Romania",
    location: "30 de judete, Romania",
    date: "Anul scolar 2026-2027 (inscrieri deschise)",
    deadline: "Inscrieri pe baza de runde",
    ageRange: "18+ ani",
    tags: ["educatie", "mentorat", "rural", "impact social"],
    isFree: true,
    url: "https://teachforromania.org/inscrieri/",
    source: "teachforromania.org",
    difficulty: "mediu",
    createdAt: "2026-02-10",
  },
  {
    id: "5",
    title: "Habitat for Humanity Romania -- Voluntariat pe Santier",
    description:
      "Voluntariaza pe santierele Habitat for Humanity, construind locuinte si centre comunitare alaturi de familii vulnerabile. Program 08:00-17:00, echipament de protectie asigurat, supervizare de constructori profesionisti.",
    category: "voluntariat",
    organization: "Habitat for Humanity Romania",
    location: "Diverse localitati, Romania",
    date: "Program continuu -- sesiuni disponibile",
    ageRange: "18+ ani",
    tags: ["constructii", "comunitate", "impact", "echipa"],
    isFree: true,
    url: "https://www.habitat.ro/implica-te/voluntariat/",
    source: "habitat.ro",
    difficulty: "mediu",
    createdAt: "2026-01-20",
  },
  {
    id: "6",
    title: "World Vision Romania -- Voluntar in Programe de Educatie",
    description:
      "Implica-te in programe de educatie, protectia copilului si dezvoltare rurala. World Vision este prezenta in comunitatile cele mai vulnerabile din Romania, oferind copiilor sanse egale la educatie de calitate.",
    category: "voluntariat",
    organization: "Fundatia World Vision Romania",
    location: "Comunitati rurale, Romania",
    date: "Program continuu",
    ageRange: "18+ ani",
    tags: ["educatie", "copii", "rural", "dezvoltare"],
    isFree: true,
    url: "https://worldvision.ro/ce-facem/",
    source: "worldvision.ro",
    difficulty: "mediu",
    createdAt: "2026-02-01",
  },
  {
    id: "21",
    title: "Ajungem Mari -- Program National de Voluntariat cu Copii",
    description:
      "Peste 1.500 de voluntari merg saptamanal la 3.500+ copii din centre de plasament. Ajuti la pregatire scolara, sustii ateliere creative, devii prieten si model. Recrutari anuale, training inclus.",
    category: "voluntariat",
    organization: "Asociatia Lindenfeld / Ajungem Mari",
    location: "National (centre de plasament)",
    date: "Program continuu -- inscrieri deschise anual",
    ageRange: "18+ ani",
    tags: ["copii", "centre de plasament", "mentorat", "educatie"],
    isFree: true,
    url: "https://www.ajungemmari.ro/voluntariat/",
    source: "ajungemmari.ro",
    difficulty: "ușor",
    createdAt: "2026-04-10",
  },
  {
    id: "22",
    title: "CONCORDIA -- Voluntar in Centre Educationale",
    description:
      "Implica-te in programele CONCORDIA pentru copii si tineri din comunitati vulnerabile. 98% din copiii din Centrele de Zi termina ciclul de invatamant. Sustine educatia prin meditatie, activitati creative si mentorat.",
    category: "voluntariat",
    organization: "Organizatia Umanitara CONCORDIA",
    location: "Bucuresti, Timisoara, Prahova",
    date: "Program continuu",
    ageRange: "18+ ani",
    tags: ["educatie", "copii vulnerabili", "centre de zi", "mentorat"],
    isFree: true,
    url: "https://www.concordia.org.ro/programe/tineri/",
    source: "concordia.org.ro",
    difficulty: "mediu",
    createdAt: "2026-04-10",
  },
  {
    id: "23",
    title: "AGLT -- Grupuri Locale de Tineret in Toata Romania",
    description:
      "Asociatia Grupurilor Locale de Tineret reuneste 30+ GLT-uri din toata tara. Tabere, zile de joaca, ateliere creative si activitati de formare pentru animatori de tineret. Invata prin joaca si descoperire in comunitate.",
    category: "voluntariat",
    organization: "AGLT -- Asociatia Grupurilor Locale de Tineret",
    location: "National (30+ comunitati)",
    date: "Program continuu",
    ageRange: "14+ ani",
    tags: ["tineret", "comunitate", "animatie", "rural"],
    isFree: true,
    url: "http://aglt.org",
    source: "aglt.org",
    difficulty: "ușor",
    createdAt: "2026-04-10",
  },
  {
    id: "24",
    title: "United Way -- Aventura prin Lectura (Voluntar)",
    description:
      "United Way Romania cauta parteneri ONG pentru proiectul Aventura prin lectura 2026. Previne analfabetismul functional in comunitati vulnerabile. Poti fi voluntar in activitati de lectura cu copiii.",
    category: "voluntariat",
    organization: "United Way Romania",
    location: "National (comunitati defavorizate)",
    date: "Aprilie - Decembrie 2026",
    ageRange: "16+ ani",
    tags: ["educatie", "lectura", "copii", "incluziune"],
    isFree: true,
    url: "https://www.unitedway.ro",
    source: "unitedway.ro",
    difficulty: "ușor",
    createdAt: "2026-04-10",
  },

  // == COMPETITII ==
  {
    id: "7",
    title: "Innovation Labs 2026 -- Hackathon National (editia a 14-a)",
    description:
      "Cel mai mare pre-accelerator de startupuri tech din Romania. Hackathon pe 21-22 martie in Bucuresti, urmat de 12 workshop-uri, 2 bootcamp-uri si Demo Day pe 25 mai. Premii investitionale de 500.000 EUR. Echipe din 25 universitati, 13 orase.",
    category: "competitii",
    organization: "Innovation Labs / Tech Lounge",
    location: "Bucuresti (Hackathon) + National",
    date: "21-22 Martie 2026 (Hackathon) -> 25 Mai 2026 (Demo Day)",
    ageRange: "18-30 ani",
    tags: ["tech", "startup", "hackathon", "inovatie"],
    isFree: true,
    url: "https://innovationlabs.ro/",
    source: "innovationlabs.ro",
    difficulty: "avansat",
    createdAt: "2026-01-10",
  },
  {
    id: "8",
    title: "Olimpiada Nationala de Informatica 2026",
    description:
      "Cea mai prestigioasa competitie de informatica din Romania, organizata de Ministerul Educatiei. Etape: locala -> judeteana -> nationala -> Lotul Olimpic. Rezolva probleme algoritmice complexe si califica-te pentru IOI.",
    category: "competitii",
    organization: "Ministerul Educatiei",
    location: "Centre judetene -> Finala Nationala",
    date: "Aprilie - Mai 2026",
    ageRange: "14-19 ani",
    tags: ["informatica", "algoritmi", "programare", "olimpiada"],
    isFree: true,
    url: "https://edu.ro",
    source: "edu.ro",
    difficulty: "avansat",
    createdAt: "2026-02-15",
  },
  {
    id: "9",
    title: "BCR Scoala de Bani -- Concurs Scoala Banilor Bine Crescuti",
    description:
      "Concurs anual de desene organizat de BCR pentru scolile din Romania. Completeaza volumele de povesti Scoala banilor bine-crescuti de Cristina Andone cu ilustratii originale. Premii pentru scoli si elevi.",
    category: "competitii",
    organization: "BCR Scoala de Bani",
    location: "Toata Romania (online + scoli)",
    date: "2026 -- inscrieri deschise",
    ageRange: "14-18 ani",
    tags: ["educatie financiara", "creativitate", "desene", "premii"],
    isFree: true,
    url: "https://www.scoaladebani.ro/scoala-banilor-bine-crescuti/concurs/",
    source: "scoaladebani.ro",
    difficulty: "ușor",
    createdAt: "2026-03-01",
  },
  {
    id: "25",
    title: "Hackathon Unplugged 2025 -- Ora de Net / Salvati Copiii",
    description:
      "Hackathon pentru adolescenti 15-18 ani organizat de Salvati Copiii Romania. 24-25 iulie la Universitatea Romano-Americana, Bucuresti. Participare gratuita. Rezolva provocari digitale in echipa.",
    category: "competitii",
    organization: "Ora de Net / Salvati Copiii Romania",
    location: "Bucuresti (Universitatea Romano-Americana)",
    date: "24-25 Iulie 2025",
    ageRange: "15-18 ani",
    tags: ["hackathon", "digital", "siguranta online", "gratuit"],
    isFree: true,
    url: "https://oradenet.ro/resurse/hackathon2025/",
    source: "oradenet.ro",
    difficulty: "mediu",
    createdAt: "2026-04-10",
  },
  {
    id: "26",
    title: "Turneul Bucurestiului -- Matematica de Performanta (Gimnaziu)",
    description:
      "Concurs online de matematica de performanta pentru gimnaziu, organizat pe olimpiade.ro, cu etape lunare. Subiecte si bareme disponibile gratuit. Pregateste-te pentru olimpiadele nationale.",
    category: "competitii",
    organization: "olimpiade.ro / SOFTWIN",
    location: "Online",
    date: "Etape lunare 2025-2026",
    ageRange: "10-15 ani",
    tags: ["matematica", "olimpiada", "concurs", "online"],
    isFree: true,
    url: "https://www.olimpiade.ro/stiri/lansam-turneul-bucure-tiului-la-matematica-de-performan-a-pentru-gimnaziu",
    source: "olimpiade.ro",
    difficulty: "avansat",
    createdAt: "2026-04-10",
  },

  // == WORKSHOPURI & CURSURI ==
  {
    id: "10",
    title: "Scoala de Bani -- Curs Gratuit de Educatie Financiara (Online)",
    description:
      "Webinar-uri online sustinute de experti financiari BCR, in fiecare joi 18:00-19:30. Cursuri disponibile: Inteligenta financiara, Securitate cibernetica, Ghid ecofinanciar, Mindfulness financiar. Platforma smart si gratuita.",
    category: "workshopuri",
    organization: "BCR Scoala de Bani",
    location: "Online (Zoom)",
    date: "In fiecare joi, 18:00-19:30",
    ageRange: "14+ ani",
    tags: ["educatie financiara", "online", "bani", "gratuit"],
    isFree: true,
    url: "https://www.scoaladebani.ro/webinar/",
    source: "scoaladebani.ro",
    difficulty: "ușor",
    createdAt: "2026-01-05",
  },
  {
    id: "11",
    title: "SALTO-YOUTH -- Training: Strengthening Volunteering in Sport",
    description:
      "Training Course Erasmus+ de 4 zile la Berlin. Dezvolta competente pentru a integra voluntariatul in activitatile sportive din comunitate. Transport, cazare si masa acoperite prin programul Erasmus+.",
    category: "workshopuri",
    organization: "SALTO-YOUTH / Erasmus+",
    location: "Berlin, Germania",
    date: "20-23 Mai 2026",
    deadline: "1 Mai 2026",
    ageRange: "18-30 ani",
    tags: ["sport", "voluntariat", "Erasmus+", "international"],
    isFree: true,
    url: "https://salto-youth.net/tools/european-training-calendar/",
    source: "salto-youth.net",
    difficulty: "mediu",
    createdAt: "2026-03-10",
  },
  {
    id: "12",
    title: "SALTO-YOUTH -- A Partnership Building Activity with Young People",
    description:
      "Activitate de construire de parteneriate in Norvegia, pentru tineri care vor sa dezvolte proiecte europene impreuna cu organizatii din alte tari. 6 zile de networking, ateliere si planificare de proiecte.",
    category: "workshopuri",
    organization: "SALTO-YOUTH / Erasmus+",
    location: "Norvegia",
    date: "15-20 Iunie 2026",
    deadline: "10 Mai 2026",
    ageRange: "18-30 ani",
    tags: ["parteneriate", "proiecte europene", "networking", "tineret"],
    isFree: true,
    url: "https://salto-youth.net/tools/european-training-calendar/",
    source: "salto-youth.net",
    difficulty: "mediu",
    createdAt: "2026-03-15",
  },
  {
    id: "13",
    title: "BCR LifeLab -- Program Educational pentru Elevi",
    description:
      "Program pilot de educatie financiara in scoli, realizat de Scoala de Bani si BCR. Elevii invata sa ia decizii financiare, sa lucreze in echipa si sa exerseze planificarea. Desfasurat pe parcursul anului scolar.",
    category: "workshopuri",
    organization: "BCR Scoala de Bani",
    location: "Scoli din Romania",
    date: "An scolar 2025-2026",
    ageRange: "14-18 ani",
    tags: ["educatie financiara", "scoala", "planificare", "echipa"],
    isFree: true,
    url: "https://www.scoaladebani.ro/lifelab/",
    source: "scoaladebani.ro",
    difficulty: "ușor",
    createdAt: "2026-02-05",
  },
  {
    id: "27",
    title: "Cantus Mundi -- Ateliere Gratuite de Cor si Percutie",
    description:
      "Cel mai mare program de integrare sociala prin muzica din Romania. 84.000+ copii, 2.500+ coruri. Atelierele corale si de percutie sunt 100% gratuite. Preselectii deschise in Bucuresti si in toata tara.",
    category: "workshopuri",
    organization: "Cantus Mundi / Corul Madrigal",
    location: "Bucuresti + National (2.500+ coruri)",
    date: "Program continuu -- preselectii deschise",
    ageRange: "6-18 ani",
    tags: ["muzica", "cor", "percutie", "gratuit"],
    isFree: true,
    url: "https://www.cantusmundi.com/preselectii",
    source: "cantusmundi.com",
    difficulty: "ușor",
    createdAt: "2026-04-10",
  },
  {
    id: "28",
    title: "Ora de Net -- Cursuri Online de Educatie Media (11-17 ani)",
    description:
      "Cursuri gratuite de educatie media si siguranta online pentru copii si adolescenti, organizate de Salvati Copiii Romania. Invata sa navighezi in siguranta, sa recunosti fake news si sa-ti protejezi imaginea online.",
    category: "workshopuri",
    organization: "Ora de Net / Salvati Copiii Romania",
    location: "Online",
    date: "2026 -- sesiuni periodice",
    ageRange: "11-17 ani",
    tags: ["educatie media", "siguranta online", "digital", "gratuit"],
    isFree: true,
    url: "https://oradenet.ro/copii-si-tineri/cursuri-si-evenimente/",
    source: "oradenet.ro",
    difficulty: "ușor",
    createdAt: "2026-04-10",
  },
  {
    id: "29",
    title: "Young Initiative -- Ambasadorii Incluziunii 2025-2026",
    description:
      "Program dedicat promovarii empatiei si incluziunii in scoli, cu 130+ cadre didactice implicate. Tinerii participa la workshop-uri de educatie non-formala, gandire critica si actiune civica. Acreditat Erasmus+.",
    category: "workshopuri",
    organization: "Asociatia Young Initiative (AYI)",
    location: "National (scoli din Romania)",
    date: "An scolar 2025-2026",
    ageRange: "14-25 ani",
    tags: ["incluziune", "empatie", "educatie non-formala", "scoala"],
    isFree: true,
    url: "https://www.younginitiative.org/opportunities/",
    source: "younginitiative.org",
    difficulty: "ușor",
    createdAt: "2026-04-10",
  },
  {
    id: "30",
    title: "Fundatia Calea Victoriei -- Cursuri pentru Adolescenti",
    description:
      "Ateliere de arta, gandire critica, debate, public speaking, design interior si fotografie. 18+ ani de activitate, certificat de participare la cerere. Sediul: Bd. Dacia 78, Bucuresti. Domenii: arte, stiinte umaniste, dezvoltare personala.",
    category: "workshopuri",
    organization: "Fundatia Calea Victoriei",
    location: "Bucuresti (Bd. Dacia 78) + Online",
    date: "Program continuu -- vezi calendarul pe site",
    ageRange: "14+ ani",
    tags: ["arta", "cultura", "dezvoltare personala", "debate"],
    isFree: false,
    price: "Variate (unele gratuite, altele cu taxa)",
    url: "https://www.fundatiacaleavictoriei.ro/category/domenii/cursuri-pentru-copii-adolescenti/",
    source: "fundatiacaleavictoriei.ro",
    difficulty: "ușor",
    createdAt: "2026-04-10",
  },

  // == EVENIMENTE ==
  {
    id: "14",
    title: "Saptamana Europeana a Tineretului 2026",
    description:
      "Eveniment organizat de ANPCDEFP la nivel national, 24 aprilie - 1 mai 2026. Activitati, dezbateri si evenimente despre participarea tinerilor la viata comunitatii si oportunitatile europene. Editie Erasmus+.",
    category: "evenimente",
    organization: "ANPCDEFP",
    location: "Bucuresti + Toata tara",
    date: "24 Aprilie - 1 Mai 2026",
    ageRange: "14-30 ani",
    tags: ["tineret", "europa", "ANPCDEFP", "participare civica"],
    isFree: true,
    url: "https://www.anpcdefp.ro/evenimente-det/vrs/IDev/2597",
    source: "anpcdefp.ro",
    difficulty: "ușor",
    createdAt: "2026-03-20",
  },
  {
    id: "15",
    title: "Ambasadori de Invatare -- Generatia 2026 (ANPCDEFP)",
    description:
      "Vrei sa faci parte din Reteaua de Ambasadori de Invatare? ANPCDEFP cauta tineri motivati care sa promoveze oportunitatile Erasmus+ in comunitatile lor. Intalnire Nationala desfasurata 26-29 martie la Bucuresti.",
    category: "evenimente",
    organization: "ANPCDEFP",
    location: "Bucuresti + Comunitati locale",
    date: "Inscrieri deschise 2026",
    ageRange: "16-30 ani",
    tags: ["Erasmus+", "ambasador", "invatare", "retea"],
    isFree: true,
    url: "https://www.anpcdefp.ro/stire/vrs/IDstire/1360",
    source: "anpcdefp.ro",
    difficulty: "ușor",
    createdAt: "2026-04-02",
  },
  {
    id: "16",
    title: "Erasmus+ Youth Exchange -- Schimb de Tineri International",
    description:
      "Schimburi de tineret finantate 100% prin Erasmus+. Participanti din 5-6 tari europene se intalnesc 7-14 zile pentru activitati de educatie non-formala, dialog intercultural si dezvoltare personala. Transport, cazare, masa incluse.",
    category: "evenimente",
    organization: "ANPCDEFP / Erasmus+",
    location: "Diverse tari europene",
    date: "Apeluri deschise pe tot parcursul anului",
    ageRange: "16-25 ani",
    tags: ["international", "cultura", "Erasmus+", "calatorii"],
    isFree: true,
    url: "https://www.erasmusplus.ro/proiecte-de-mobilitate",
    source: "erasmusplus.ro",
    difficulty: "ușor",
    createdAt: "2026-02-20",
  },
  {
    id: "20",
    title: "Runners for Humanity 2026 -- Habitat for Humanity",
    description:
      "Eveniment sportiv de fundraising organizat de Habitat for Humanity Romania. Alergare caritabila -- fiecare kilometru contribuie la constructia de locuinte pentru familii vulnerabile. Participare si ca voluntar organizator.",
    category: "evenimente",
    organization: "Habitat for Humanity Romania",
    location: "Romania (diverse orase)",
    date: "2026 -- Date de anuntat",
    ageRange: "14+ ani",
    tags: ["sport", "fundraising", "caritate", "alergare"],
    isFree: false,
    price: "Taxa de participare (vezi site)",
    url: "https://fundraiser.habitat.ro/eveniment/runners-for-humanity-2026",
    source: "habitat.ro",
    difficulty: "ușor",
    createdAt: "2026-03-01",
  },
  {
    id: "31",
    title: "Young Initiative -- Proiectul European SPROUT (Rezilienta Climatica)",
    description:
      "Proiect Erasmus+ care pune tinerii in prim-planul adaptarii la schimbarile climatice. Practici sustenabile si oportunitati pentru tranzitia eco-sociala in comunitati urbane si rurale. Mobilitati internationale incluse.",
    category: "evenimente",
    organization: "Asociatia Young Initiative (AYI)",
    location: "Romania + Parteneri europeni",
    date: "2026 -- in derulare",
    ageRange: "16-30 ani",
    tags: ["mediu", "clima", "Erasmus+", "sustenabilitate"],
    isFree: true,
    url: "https://www.younginitiative.org/incepe-proiectul-european-sprout-dedicat-adaptarii-la-efectele-schimbarilor-climatice/",
    source: "younginitiative.org",
    difficulty: "mediu",
    createdAt: "2026-04-10",
  },
  {
    id: "32",
    title: "Opera Comica pentru Copii -- Future Leaders Get Together",
    description:
      "Conferinta pentru tineri lideri, editia a III-a, organizata la Opera Comica pentru Copii din Bucuresti. Spectacole de opera, balet si musical adaptate tinerilor, plus ateliere Micul Artist si festivaluri culturale.",
    category: "evenimente",
    organization: "Opera Comica pentru Copii",
    location: "Bucuresti (Calea Giulesti nr. 16)",
    date: "2026 -- vezi programul pe site",
    ageRange: "6-18 ani",
    tags: ["cultura", "opera", "arta", "leadership"],
    isFree: false,
    price: "Bilete de la 20 lei",
    url: "https://operacomica.ro/spectacole/program/",
    source: "operacomica.ro",
    difficulty: "ușor",
    createdAt: "2026-04-10",
  },
  {
    id: "33",
    title: "Eurodesk Romania -- DiscoverEU Meet-up Lyon 2026",
    description:
      "Primul meet-up DiscoverEU de mare amploare! 16-18 iulie, Lyon, Franta. Calatoresti gratuit cu trenul prin Europa (18 ani), participi la activitati de invatare si networking cu tineri din toata UE.",
    category: "evenimente",
    organization: "Eurodesk Romania / ANPCDEFP",
    location: "Lyon, Franta (plecare din Romania)",
    date: "16-18 Iulie 2026",
    ageRange: "18 ani",
    tags: ["DiscoverEU", "calatorie", "europa", "networking"],
    isFree: true,
    url: "https://www.eurodesk.ro/stire/vrs/IDstire/1359",
    source: "eurodesk.ro",
    difficulty: "ușor",
    createdAt: "2026-04-10",
  },

  // == TABERE ==
  {
    id: "17",
    title: "Let's Do It, Romania! -- Doers School",
    description:
      "Program educational premiat la Gala Green Report pentru excelenta in educatia de mediu. Tabara de vara + ateliere sustenabile pe tot parcursul anului. Invata despre ecologie, reciclare si actiune civica.",
    category: "tabere",
    organization: "Let's Do It, Romania!",
    location: "Diverse locatii, Romania",
    date: "Vara 2026",
    ageRange: "14-18 ani",
    tags: ["ecologie", "educatie", "sustenabilitate", "natura"],
    isFree: true,
    url: "https://letsdoitromania.ro/",
    source: "letsdoitromania.ro",
    difficulty: "ușor",
    createdAt: "2026-02-04",
  },
  {
    id: "34",
    title: "Ajungem Mari -- Tabere de Dezvoltare Personala",
    description:
      "Tabere de dezvoltare personala si viata independenta pentru copii si tineri din centre de plasament si medii defavorizate. Drumetii, seri tematice, jocuri de echipa, improvizatie. Voluntarii sunt bineveniti.",
    category: "tabere",
    organization: "Asociatia Lindenfeld / Ajungem Mari",
    location: "Diverse locatii, Romania",
    date: "Vara 2026",
    ageRange: "14-24 ani",
    tags: ["dezvoltare personala", "viata independenta", "campanie", "echipa"],
    isFree: true,
    url: "https://www.ajungemmari.ro/proiecte/evadare-pentru-dezvoltare/",
    source: "ajungemmari.ro",
    difficulty: "ușor",
    createdAt: "2026-04-10",
  },

  // == BURSE & FINANTARI ==
  {
    id: "18",
    title: "Corpul European de Solidaritate -- Proiecte de Solidaritate 2026",
    description:
      "Finantare UE pentru grupuri informale de tineri care vor sa initieze proiecte locale de solidaritate. Buget de pana la 500 EUR/luna/voluntar. Ghidul si Apelul ESC 2026 au fost lansate.",
    category: "burse",
    organization: "Corpul European de Solidaritate / ANPCDEFP",
    location: "Romania (proiecte locale)",
    date: "Termen limita: runde multiple 2026",
    deadline: "Vezi suntsolidar.eu pentru termene",
    ageRange: "18-30 ani",
    tags: ["finantare", "proiecte locale", "solidaritate", "UE"],
    isFree: true,
    url: "https://www.suntsolidar.eu/",
    source: "suntsolidar.eu",
    difficulty: "mediu",
    createdAt: "2026-01-25",
  },
  {
    id: "19",
    title: "Erasmus+ -- Finantare Proiecte de Tineret 2026",
    description:
      "Buget total UE de peste 14 miliarde euro. Romania a primit ~78 milioane euro/an pentru proiecte. Mobilitati, parteneriate strategice si dialog structurat pentru tineri. Aplicatii prin intermediul ANPCDEFP.",
    category: "burse",
    organization: "ANPCDEFP / Erasmus+",
    location: "Romania + International",
    date: "Apeluri 2026 deschise",
    ageRange: "16-30 ani",
    tags: ["Erasmus+", "finantare", "proiecte", "international"],
    isFree: true,
    url: "https://www.anpcdefp.ro/erasmusplus/",
    source: "anpcdefp.ro",
    difficulty: "mediu",
    createdAt: "2026-01-01",
  },
  {
    id: "35",
    title: "Fundatia Calea Victoriei -- Burse pentru Elevi si Studenti",
    description:
      "Burse educationale pentru elevi si studenti oferite de Fundatia Calea Victoriei. Acces la cursuri de arta, cultura, gandire critica, debate si dezvoltare personala. Candidaturile se depun pe site.",
    category: "burse",
    organization: "Fundatia Calea Victoriei",
    location: "Bucuresti (Bd. Dacia 78) + Online",
    date: "Inscrieri periodice -- vezi site",
    ageRange: "14-25 ani",
    tags: ["bursa", "educatie", "cultura", "dezvoltare"],
    isFree: true,
    url: "https://www.fundatiacaleavictoriei.ro/burse/",
    source: "fundatiacaleavictoriei.ro",
    difficulty: "mediu",
    createdAt: "2026-04-10",
  },
];

// ============================================================
// SURSE DE DATE -- URL-uri verificate, Mai 2026
// ============================================================

export const dataSources: DataSource[] = [
  {
    id: "anpcdefp",
    name: "ANPCDEFP",
    url: "https://www.anpcdefp.ro",
    category: ["voluntariat", "evenimente", "burse"],
    type: "scraping",
    description:
      "Agentia Nationala Erasmus+ si Corpul European de Solidaritate. Gestioneaza bugetul de ~78M EUR/an pentru Romania.",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 150,
  },
  {
    id: "suntsolidar",
    name: "Sunt Solidar (ESC Romania)",
    url: "https://www.suntsolidar.eu",
    category: ["voluntariat", "burse"],
    type: "scraping",
    description:
      "Portalul oficial ESC Romania -- proiecte de voluntariat si solidaritate finantate de UE",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 80,
  },
  {
    id: "erasmusplus-ro",
    name: "Erasmus+ Romania",
    url: "https://www.erasmusplus.ro",
    category: ["voluntariat", "evenimente", "burse"],
    type: "scraping",
    description:
      "Site oficial Erasmus+ RO -- mobilitati, schimburi de tineri, parteneriate strategice",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 200,
  },
  {
    id: "salto-youth",
    name: "SALTO-YOUTH",
    url: "https://salto-youth.net/tools/european-training-calendar/",
    category: ["evenimente", "workshopuri"],
    type: "scraping",
    description:
      "Calendarul European de Training-uri -- 92+ training-uri upcoming verificate",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 92,
  },
  {
    id: "eurodesk",
    name: "Eurodesk",
    url: "https://programmes.eurodesk.eu",
    category: ["voluntariat", "evenimente", "burse"],
    type: "scraping",
    description:
      "Agregator european de oportunitati pentru tineri, parteneri cu Comisia Europeana",
    isActive: true,
    opportunityCount: 400,
  },
  {
    id: "innovation-labs",
    name: "Innovation Labs",
    url: "https://innovationlabs.ro",
    category: ["competitii", "workshopuri"],
    type: "scraping",
    description:
      "Pre-accelerator tech -- editia 14, 768 echipe sustinute, 500K EUR premii, 25 universitati",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 15,
  },
  {
    id: "lets-do-it-romania",
    name: "Let's Do It, Romania!",
    url: "https://letsdoitromania.ro",
    category: ["voluntariat", "tabere"],
    type: "scraping",
    description:
      "Cea mai mare miscare sociala din Romania -- Ziua de Curatenie Nationala + Doers School",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 10,
  },
  {
    id: "crucea-rosie",
    name: "Crucea Rosie Romana",
    url: "https://crucearosie.ro/implica-te/voluntariat/",
    category: ["voluntariat"],
    type: "scraping",
    description:
      "149 ani de umanitate. 6.000+ voluntari, prim ajutor, sprijin in dezastre, actiuni sociale",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 50,
  },
  {
    id: "teach-for-romania",
    name: "Teach for Romania",
    url: "https://teachforromania.org",
    category: ["voluntariat"],
    type: "scraping",
    description:
      "12 generatii, 30 judete, 336 scoli, 38.000 copii. Program de 2 ani la catedra.",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 5,
  },
  {
    id: "habitat-humanity",
    name: "Habitat for Humanity RO",
    url: "https://www.habitat.ro/implica-te/voluntariat/",
    category: ["voluntariat"],
    type: "scraping",
    description:
      "Constructie de locuinte, voluntariat pe santier, proiecte comunitare. Include Runners for Humanity.",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 20,
  },
  {
    id: "world-vision",
    name: "World Vision Romania",
    url: "https://worldvision.ro",
    category: ["voluntariat"],
    type: "scraping",
    description:
      "Educatie, protectia copilului si dezvoltare rurala. 90,7% buget in activitati directe.",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 30,
  },
  {
    id: "scoala-de-bani",
    name: "BCR Scoala de Bani",
    url: "https://www.scoaladebani.ro",
    category: ["workshopuri", "competitii"],
    type: "scraping",
    description:
      "Educatie financiara gratuita -- 10+ cursuri online, webinarii joi 18:00, LifeLab in scoli, concurs national",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 15,
  },
  {
    id: "proedus",
    name: "ProEdus",
    url: "https://www.proedus.ro",
    category: ["workshopuri", "evenimente"],
    type: "scraping",
    description:
      "Platforma educationala cu cursuri, workshop-uri si resurse pentru tineri din Romania",
    isActive: false,
    opportunityCount: 0,
  },
  {
    id: "edu-ro",
    name: "Ministerul Educatiei",
    url: "https://edu.ro",
    category: ["competitii", "burse"],
    type: "scraping",
    description:
      "Olimpiade nationale (informatica, matematica, fizica, etc.), concursuri si burse oficiale",
    isActive: true,
    opportunityCount: 80,
  },
  {
    id: "junior-achievement",
    name: "Junior Achievement Romania",
    url: "https://www.jaromania.org",
    category: ["workshopuri", "competitii"],
    type: "scraping",
    description:
      "Programe de educatie antreprenoriala pentru liceeni -- Compania de Exercitiu, innovation camps",
    isActive: false,
    opportunityCount: 60,
  },
  {
    id: "bursa-studiu",
    name: "BursaDeStudiu.ro",
    url: "https://bursadestudiu.ro",
    category: ["burse"],
    type: "scraping",
    description: "Burse de studii din Romania si internationale",
    isActive: true,
    opportunityCount: 120,
  },
  {
    id: "fundatia-comunitara",
    name: "Fundatia pentru Comunitate",
    url: "https://fundatiacomunitara.ro",
    category: ["burse"],
    type: "scraping",
    description: "Granturi si finantari pentru proiecte de tineri",
    isActive: true,
    opportunityCount: 40,
  },
  // -- NOI SURSE (Mai 2026) --
  {
    id: "cantus-mundi",
    name: "Cantus Mundi",
    url: "https://www.cantusmundi.com",
    category: ["workshopuri", "evenimente"],
    type: "scraping",
    description:
      "Cel mai mare program de integrare sociala prin muzica. 84.000+ copii, 2.500+ coruri, ateliere gratuite. Partener: Corul Madrigal",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 30,
  },
  {
    id: "oradenet",
    name: "Ora de Net / Salvati Copiii",
    url: "https://oradenet.ro",
    category: ["workshopuri", "competitii"],
    type: "scraping",
    description:
      "Educatie digitala si siguranta online pentru copii si tineri. Hackathoane, cursuri media, Debate Spot. Program al Salvati Copiii Romania",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 15,
  },
  {
    id: "ajungem-mari",
    name: "Ajungem Mari",
    url: "https://www.ajungemmari.ro",
    category: ["voluntariat", "tabere"],
    type: "scraping",
    description:
      "1.500+ voluntari, 3.500+ copii din centre de plasament. Voluntariat saptamanal, cursuri vocationale, tabere de dezvoltare personala",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 20,
  },
  {
    id: "young-initiative",
    name: "Asociatia Young Initiative (AYI)",
    url: "https://www.younginitiative.org",
    category: ["workshopuri", "evenimente"],
    type: "scraping",
    description:
      "Educatie non-formala, acreditat Erasmus+, membru YMCA Romania. Programe: Ambasadorii Incluziunii, SPROUT, mobilitati internationale",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 25,
  },
  {
    id: "concordia",
    name: "CONCORDIA Romania",
    url: "https://www.concordia.org.ro",
    category: ["voluntariat", "workshopuri"],
    type: "scraping",
    description:
      "Programe pentru copii, tineri si comunitate. 98% rata absolvire in Centrele de Zi. Mobilitati Erasmus+, proiecte educationale",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 30,
  },
  {
    id: "aglt",
    name: "AGLT - Grupuri Locale de Tineret",
    url: "http://aglt.org",
    category: ["voluntariat", "tabere"],
    type: "scraping",
    description:
      "30+ grupuri locale de tineret din toata Romania. Tabere, ateliere creative, activitati de formare si animatie de tineret",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 15,
  },
  {
    id: "united-way",
    name: "United Way Romania",
    url: "https://www.unitedway.ro",
    category: ["voluntariat", "evenimente"],
    type: "scraping",
    description:
      "Educatie, sanatate, venituri. Proiecte: Aventura prin lectura, NutriCOOLtura, sprijin comunitati vulnerabile",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 20,
  },
  {
    id: "fundatia-calea-victoriei",
    name: "Fundatia Calea Victoriei",
    url: "https://www.fundatiacaleavictoriei.ro",
    category: ["workshopuri", "burse"],
    type: "scraping",
    description:
      "18+ ani de activitate. Cursuri de arta, cultura, gandire critica, debate, dezvoltare personala. Burse pentru elevi si studenti",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 40,
  },
  {
    id: "opera-comica",
    name: "Opera Comica pentru Copii",
    url: "https://operacomica.ro",
    category: ["evenimente"],
    type: "scraping",
    description:
      "Opera, balet, musical pentru copii si tineri. Ateliere Micul Artist, festivaluri (Bebe Fest, Cartilor Deschise), conferinta Future Leaders",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 50,
  },
  {
    id: "eurodesk-ro",
    name: "Eurodesk Romania",
    url: "https://www.eurodesk.ro",
    category: ["burse", "evenimente", "voluntariat"],
    type: "scraping",
    description:
      "Portalul national Eurodesk, gestionat de ANPCDEFP. Burse, stagii, concursuri, finantari UE, DiscoverEU, Saptamana Tineretului",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 100,
  },
  {
    id: "olimpiade-ro",
    name: "olimpiade.ro",
    url: "https://www.olimpiade.ro",
    category: ["competitii"],
    type: "scraping",
    description:
      "Olimpiade si concursuri scolare: matematica, informatica, istorie, fizica, limbi straine. Subiecte, bareme si calendar competitii",
    isActive: true,
    lastSync: "2026-04-10",
    opportunityCount: 50,
  },
  {
    id: "studinfo",
    name: "StudInfo.ro",
    url: "https://www.studinfo.ro",
    category: ["burse", "evenimente"],
    type: "scraping",
    description:
      "Portal cu informatii pentru elevi si studenti: burse, concursuri, evenimente educationale, ghiduri universitare",
    isActive: false,
    opportunityCount: 0,
  },
  {
    id: "burse-ro",
    name: "Burse.ro",
    url: "https://www.burse.ro",
    category: ["burse"],
    type: "scraping",
    description:
      "Agregator de burse de studiu nationale si internationale pentru elevi, studenti si cercetatori",
    isActive: false,
    opportunityCount: 0,
  },
  // -- NOI SURSE (Aprilie 2026) --
  {
    id: "salvati-copiii",
    name: "Salvați Copiii România",
    url: "https://www.salvaticopiii.ro",
    category: ["voluntariat", "workshopuri"],
    type: "scraping",
    description:
      "Cea mai mare organizatie neguvernamentala dedicata drepturilor copilului. Programe de educatie, sanatate si protectie",
    isActive: true,
    lastSync: "2026-04-12",
    opportunityCount: 40,
  },
  {
    id: "sos-satele",
    name: "SOS Satele Copiilor",
    url: "https://www.sos-satelecopiilor.ro",
    category: ["voluntariat"],
    type: "scraping",
    description:
      "Sprijin pentru copii si tineri fara parinti. Voluntariat, mentorat, programe de integrare sociala",
    isActive: true,
    lastSync: "2026-04-12",
    opportunityCount: 15,
  },
  {
    id: "aiesec",
    name: "AIESEC România",
    url: "https://aiesec.ro",
    category: ["voluntariat", "evenimente"],
    type: "scraping",
    description:
      "Cea mai mare organizatie de tineret din lume. Voluntariat international, stagii si leadership in 120+ tari",
    isActive: true,
    lastSync: "2026-04-12",
    opportunityCount: 80,
  },
  {
    id: "code4romania",
    name: "Code for Romania",
    url: "https://code4.ro",
    category: ["workshopuri", "evenimente", "competitii"],
    type: "scraping",
    description:
      "Civic tech: hackathoane civice, workshop-uri de programare, proiecte open-source pentru Romania",
    isActive: true,
    lastSync: "2026-04-12",
    opportunityCount: 25,
  },
  {
    id: "greenpeace-ro",
    name: "Greenpeace România",
    url: "https://www.greenpeace.org/romania/",
    category: ["voluntariat", "evenimente"],
    type: "scraping",
    description:
      "Campanii pentru protectia mediului: paduri, poluare, energie curata, biodiversitate",
    isActive: true,
    lastSync: "2026-04-12",
    opportunityCount: 20,
  },
  {
    id: "wwf-ro",
    name: "WWF România",
    url: "https://wwf.ro",
    category: ["voluntariat", "evenimente"],
    type: "scraping",
    description:
      "Conservarea naturii: plantat copaci, monitorizare biodiversitate, educatie ecologica in arii protejate",
    isActive: true,
    lastSync: "2026-04-12",
    opportunityCount: 15,
  },
  {
    id: "etwinning",
    name: "eTwinning România",
    url: "https://etwinning.ro",
    category: ["workshopuri"],
    type: "scraping",
    description:
      "Proiecte educationale internationale online (Erasmus+). Colaborari intre scoli din 44 de tari",
    isActive: true,
    lastSync: "2026-04-12",
    opportunityCount: 60,
  },
  {
    id: "activecitizensfund",
    name: "Active Citizens Fund România",
    url: "https://activecitizensfund.ro",
    category: ["burse"],
    type: "scraping",
    description:
      "Granturi pentru ONG-uri: cetatenie activa, drepturile omului, incluziune. Finantat de Norvegia/Islanda/Liechtenstein",
    isActive: true,
    lastSync: "2026-04-12",
    opportunityCount: 30,
  },
  {
    id: "frds",
    name: "FRDS - Fondul Român de Dezvoltare Socială",
    url: "https://www.frfrds.ro",
    category: ["burse", "workshopuri"],
    type: "scraping",
    description:
      "Programe pentru tineri NEET: cursuri de calificare, consiliere, stagii platite, antreprenoriat",
    isActive: true,
    lastSync: "2026-04-12",
    opportunityCount: 20,
  },
  {
    id: "asociatia-magic",
    name: "Asociația Magic",
    url: "https://www.asociatiamagic.ro",
    category: ["voluntariat"],
    type: "scraping",
    description:
      "Voluntariat in spitalele de copii. Terapie prin joaca, animatie si suport emotional in 20+ spitale",
    isActive: true,
    lastSync: "2026-04-12",
    opportunityCount: 10,
  },
  {
    id: "daruieste-viata",
    name: "Dăruiește Viață",
    url: "https://www.daruiesteviata.ro",
    category: ["voluntariat"],
    type: "scraping",
    description:
      "A construit primul spital public din donatii. Campanii de donare, voluntariat, proiecte comunitare de sanatate",
    isActive: true,
    lastSync: "2026-04-12",
    opportunityCount: 10,
  },
  {
    id: "ymca-ro",
    name: "YMCA România",
    url: "https://ymca.ro",
    category: ["voluntariat", "tabere"],
    type: "scraping",
    description:
      "Centre de tineret in 10 orase. Sport, educatie, cultura, dezvoltare comunitara. 180+ ani de traditie",
    isActive: true,
    lastSync: "2026-04-12",
    opportunityCount: 20,
  },
  {
    id: "natieprineducatie",
    name: "Nație prin Educație (FIRST România)",
    url: "https://natieprineducatie.ro",
    category: ["competitii"],
    type: "scraping",
    description:
      "Competitii internationale de robotica FIRST Tech Challenge. Design, constructie si programare de roboti",
    isActive: true,
    lastSync: "2026-04-12",
    opportunityCount: 5,
  },
  {
    id: "registrul-ong",
    name: "Registrul ONG (Ministerul Justiției)",
    url: "https://www.just.ro/registrul-national-ong/",
    category: ["voluntariat"],
    type: "scraping",
    description:
      "Registrul National al ONG-urilor din Romania. Lista oficiala a asociatiilor si fundatiilor inregistrate",
    isActive: false,
    opportunityCount: 0,
  },
  {
    id: "anaf-formularul-230",
    name: "ANAF - Lista entități Formularul 230",
    url: "https://www.anaf.ro/anaf/internet/ANAF/informatii_publice/informatii_3.5/",
    category: ["voluntariat"],
    type: "scraping",
    description:
      "Lista ONG-urilor eligibile pentru directia 3.5% din impozit (Formularul 230). Sursa ANAF pentru identificarea asociatiilor active",
    isActive: false,
    opportunityCount: 0,
  },
];
