-- ================================================
-- DirecțiaTa -- Oportunități NOI (Aprilie 2026)
-- Rulează acest SQL în Supabase SQL Editor
-- ================================================
-- Surse noi: voluntar.gov.ro, FDSC, FRDS, NGO Hub,
-- Salvati Copiii, SOS Satele Copiilor, MedLife / Peditel,
-- Junior Achievement, eTwinning, CEV, YMCA Romania,
-- Olimpiade.ro diverse, Active Citizens Fund, Greenpeace,
-- WWF Romania, AIESEC, ELSA Romania
-- ================================================

INSERT INTO opportunities (title, description, category, organization, location, date, deadline, age_range, tags, is_free, price, url, source, difficulty, status, created_at) VALUES

-- === VOLUNTARIAT NOU ===
('SOS Satul Copiilor -- Voluntar Mentor', 'Devino mentor in programele SOS Satele Copiilor Romania. Sprijina copii si tineri care cresc fara parinti prin activitati educationale, recreative si de dezvoltare personala. Training gratuit, supervizare continua.', 'voluntariat', 'SOS Satele Copiilor Romania', 'Bucuresti, Cluj, Sibiu, Timisoara', 'Program continuu -- inscrieri deschise', NULL, '18+ ani', ARRAY['copii', 'mentorat', 'educatie', 'familie'], true, NULL, 'https://www.sos-satelecopiilor.ro/implica-te/voluntariat/', 'sos-satelecopiilor.ro', 'mediu', 'approved', '2026-04-12'),

('Salvati Copiii Romania -- Voluntar in Programe Nationale', 'Cea mai mare organizatie neguvernamentala dedicata drepturilor copilului din Romania. Voluntariaza in programe de educatie, sanatate, protectie si raspuns la urgente. Peste 5 milioane de copii ajutati anual.', 'voluntariat', 'Salvati Copiii Romania', 'National (30+ centre)', 'Program continuu', NULL, '16+ ani', ARRAY['copii', 'drepturi', 'educatie', 'protectie'], true, NULL, 'https://www.salvaticopiii.ro/implica-te/voluntariat', 'salvaticopiii.ro', 'usor', 'approved', '2026-04-12'),

('AIESEC Romania -- Voluntariat International', 'AIESEC este cea mai mare organizatie de tineret din lume. Participa la proiecte de voluntariat international in peste 120 de tari si regiuni. Dezvoltare de leadership, schimb intercultural, impact social measurabil.', 'voluntariat', 'AIESEC Romania', 'International (120+ tari)', 'Proiecte pe tot parcursul anului', NULL, '18-30 ani', ARRAY['international', 'leadership', 'tineret', 'calatorii'], true, NULL, 'https://aiesec.ro/', 'aiesec.ro', 'mediu', 'approved', '2026-04-12'),

('Greenpeace Romania -- Voluntar Activ', 'Alatura-te comunitatii de voluntari Greenpeace Romania. Campanii pentru protectia padurilor, reducerea poluarii, energie curata si protejarea biodiversitatii. Actiuni de stanga, petitii, flash mob-uri si educatie ecologica.', 'voluntariat', 'Greenpeace Romania', 'Bucuresti + National', 'Program continuu', NULL, '16+ ani', ARRAY['mediu', 'ecologie', 'activism', 'paduri'], true, NULL, 'https://www.greenpeace.org/romania/implica-te/', 'greenpeace.org/romania', 'usor', 'approved', '2026-04-12'),

('WWF Romania -- Voluntar pentru Natura', 'Programul de voluntariat WWF Romania: plantat de copaci, curatenie in arii protejate, monitorizare biodiversitate si educatie de mediu. Romania gazduieste 50% din populatia de ursi bruni din UE.', 'voluntariat', 'WWF Romania', 'Arii protejate, Romania', 'Campanii sezoniere', NULL, '16+ ani', ARRAY['natura', 'biodiversitate', 'conservare', 'mediu'], true, NULL, 'https://wwf.ro/implica-te/', 'wwf.ro', 'usor', 'approved', '2026-04-12'),

('Asociatia Magic -- Voluntar in Spitalele de Copii', 'Asociatia Magic aduce bucurie in spitalele de copii din Romania. Voluntari dresati in terapia prin joaca, animatie si suport emotional. Prezenta in 20+ spitale, peste 20.000 de copii beneficiari anual.', 'voluntariat', 'Asociatia Magic', 'Spitale pediatrice, Romania', 'Program continuu -- training trimestrial', NULL, '18+ ani', ARRAY['sanatate', 'copii', 'spital', 'terapie prin joaca'], true, NULL, 'https://www.asociatiamagic.ro/voluntariat/', 'asociatiamagic.ro', 'mediu', 'approved', '2026-04-12'),

('YMCA Romania -- Voluntariat Comunitar', 'YMCA Romania ofera programe de voluntariat in centre de tineret din 10 orase. Activitati sportive, educationale, culturale si de dezvoltare comunitara. Membru al YMCA Europe cu peste 180 ani de traditie.', 'voluntariat', 'YMCA Romania', '10 orase din Romania', 'Program continuu', NULL, '14+ ani', ARRAY['sport', 'tineret', 'comunitate', 'educatie'], true, NULL, 'https://ymca.ro/voluntariat/', 'ymca.ro', 'usor', 'approved', '2026-04-12'),

('Daruieste Viata -- Voluntar in Proiecte de Sanatate', 'Asociatia Daruieste Viata a construit primul spital public din donatii in Romania. Voluntariaza in campanii de donare, logistica, comunicare si proiecte comunitare de sanatate.', 'voluntariat', 'Asociatia Daruieste Viata', 'Bucuresti', 'Program continuu', NULL, '18+ ani', ARRAY['sanatate', 'spital', 'donare', 'comunitate'], true, NULL, 'https://www.daruiesteviata.ro/implicate', 'daruiesteviata.ro', 'mediu', 'approved', '2026-04-12'),

-- === EVENIMENTE NOI ===
('iTEC 2026 -- International Teenagers Conference', 'Conferinta internationala pentru adolescenti organizata la Cluj-Napoca. Workshop-uri, talk-uri inspirationale, networking si proiecte creative. Editia a VI-a, participanti din 15 tari.', 'evenimente', 'iTEC Romania', 'Cluj-Napoca', 'Iunie 2026', '15 Mai 2026', '14-19 ani', ARRAY['conferinta', 'international', 'tineret', 'inspiratie'], true, NULL, 'https://itecromania.ro/', 'itecromania.ro', 'usor', 'approved', '2026-04-12'),

('TEDxYouth Bucharest 2026', 'Eveniment TEDx dedicat tinerilor din Bucuresti. Talk-uri de 18 minute pe teme de inovatie, stiinta, arta si impact social. Atmosfera inspirationala, networking cu lideri si inovatori.', 'evenimente', 'TEDxYouth@Bucharest', 'Bucuresti', 'Octombrie 2026', NULL, '14-25 ani', ARRAY['TEDx', 'inspiratie', 'inovatie', 'stiinta'], false, 'Bilete de la 30 lei', 'https://tedxyouthbucharest.com/', 'tedxyouthbucharest.com', 'usor', 'approved', '2026-04-12'),

('Noaptea Cercetatorilor 2026', 'Cel mai mare eveniment de popularizare a stiintei din Romania, parte din Noaptea Europeana a Cercetatorilor. Laboratoare deschise, experimente live, intalniri cu cercetatori, in 20+ orase din Romania.', 'evenimente', 'Comisia Europeana / Universitati din Romania', '20+ orase din Romania', '25 Septembrie 2026', NULL, '14+ ani', ARRAY['stiinta', 'cercetare', 'experimente', 'universitate'], true, NULL, 'https://noapteacercetatorilor.ro/', 'noapteacercetatorilor.ro', 'usor', 'approved', '2026-04-12'),

('Code for Romania -- Civic Hackathon 2026', 'Hackathon civic organizat de Code for Romania. Dezvolta solutii tech pentru probleme reale ale societatii romanesti. Echipe multidisciplinare, mentori din industrie, premii si implementare reala a proiectelor.', 'evenimente', 'Code for Romania', 'Bucuresti + Online', 'Noiembrie 2026', NULL, '16+ ani', ARRAY['hackathon', 'civic tech', 'programare', 'impact social'], true, NULL, 'https://code4.ro/', 'code4.ro', 'mediu', 'approved', '2026-04-12'),

('Festivalul de Film NexT 2026', 'Festival international de film de scurt metraj pentru tineri cineasti. Proiectii, workshop-uri de regie, montaj si scenariu, intalniri cu profesionisti din industrie. Sectiune competitionala dedicata tinerilor sub 25.', 'evenimente', 'NexT Film Festival', 'Bucuresti', 'Mai 2026', NULL, '16+ ani', ARRAY['film', 'arta', 'creativitate', 'festival'], false, 'Bilete de la 15 lei', 'https://nextfilmfestival.ro/', 'nextfilmfestival.ro', 'usor', 'approved', '2026-04-12'),

-- === WORKSHOPURI NOI ===
('eTwinning Romania -- Ateliere Internationale Online', 'Proiecte educationale internationale prin platforma eTwinning (Erasmus+). Elevi si profesori din 44 de tari colaboreaza in proiecte online de STEM, arte, limbi straine si cetatenie activa. 100% gratuit.', 'workshopuri', 'eTwinning / ANPCDEFP', 'Online', 'An scolar 2026-2027', NULL, '10-19 ani', ARRAY['eTwinning', 'international', 'educatie', 'online'], true, NULL, 'https://etwinning.ro/', 'etwinning.ro', 'usor', 'approved', '2026-04-12'),

('Junior Achievement -- Compania de Exercitiu', 'Programul educational JA Romania pentru liceeni. Invata sa creezi un business de la 0: plan de afaceri, marketing, finante, Management. 30.000+ elevi participanti anual. Competitie nationala + europeana.', 'workshopuri', 'Junior Achievement Romania', 'National (licee din Romania)', 'An scolar 2025-2026', NULL, '15-19 ani', ARRAY['antreprenoriat', 'business', 'educatie', 'competitie'], true, NULL, 'https://www.jaromania.org/programele-ja/compania-de-exercitiu', 'jaromania.org', 'mediu', 'approved', '2026-04-12'),

('ELSA Romania -- Sesiuni de Drepturile Omului pentru Tineri', 'ELSA (European Law Students Association) Romania ofera workshop-uri gratuite de educatie juridica: drepturile omului, cetatenie europeana, acces la justitie. Predate de studenti la drept.', 'workshopuri', 'ELSA Romania', 'Universitati din Romania + Online', 'Program continuu', NULL, '14+ ani', ARRAY['drepturile omului', 'educatie juridica', 'cetatenie', 'UE'], true, NULL, 'https://elsa-romania.org/', 'elsa-romania.org', 'usor', 'approved', '2026-04-12'),

('Code for Romania -- Tech for Social Good Workshop', 'Workshop-uri lunare organizate de Code for Romania. Invata React, Python, data science, UX/UI design in contextul proiectelor civice. Mentori voluntari din companiile tech de top din Romania.', 'workshopuri', 'Code for Romania', 'Online (Zoom) + Bucuresti', 'Lunar', NULL, '16+ ani', ARRAY['programare', 'civic tech', 'React', 'design'], true, NULL, 'https://code4.ro/ro/implica-te', 'code4.ro', 'mediu', 'approved', '2026-04-12'),

-- === COMPETITII NOI ===
('Olimpiada Nationala de Matematica 2026', 'Competitie de matematica organizata de Ministerul Educatiei. Etape: locala -> judeteana -> nationala -> Lotul Olimpic International (IMO). Subiecte provocatoare, pregatire de elita, promovare academica.', 'competitii', 'Ministerul Educatiei', 'Centre judetene -> Finala Nationala', 'Februarie - Mai 2026', NULL, '14-19 ani', ARRAY['matematica', 'olimpiada', 'algoritmi', 'excelenta'], true, NULL, 'https://edu.ro', 'edu.ro', 'avansat', 'approved', '2026-04-12'),

('National Science Olympiad Romania 2026', 'Olimpiadele nationale de fizica, chimie si biologie. Etape succesive cu subiecte din materia de liceu si materie olimpica. Promoveaza tineri spre loturi internationale si cariere STEM.', 'competitii', 'Ministerul Educatiei', 'National', 'Martie - Mai 2026', NULL, '14-19 ani', ARRAY['stiinta', 'fizica', 'chimie', 'biologie'], true, NULL, 'https://edu.ro', 'edu.ro', 'avansat', 'approved', '2026-04-12'),

('FIRST Tech Challenge Romania 2026', 'Competitie internationala de robotica pentru echipe de liceeni. Design, constructie si programare de roboti care rezolva provocari reale. Calificari la Campionatul Mondial FIRST din SUA.', 'competitii', 'FIRST Romania / Natie prin Educatie', 'National -> International', 'Octombrie 2026 - Aprilie 2027', NULL, '14-18 ani', ARRAY['robotica', 'STEM', 'inginerie', 'international'], true, NULL, 'https://www.firstinspires.org/robotics/ftc', 'natieprineducatie.ro', 'avansat', 'approved', '2026-04-12'),

-- === TABERE NOI ===
('Tabara Internationala de Tineret -- Sulina 2026', 'Tabara internationala de vara la Sulina, in Delta Dunarii. Activitati ecologice, sporturi nautice, observare de pasari, ateliere de fotografie nature, voluntariat in arii protejate.', 'tabere', 'Asociatia Ivan Patzaichin', 'Sulina, Delta Dunarii', 'Iulie 2026', '15 Iunie 2026', '14-25 ani', ARRAY['natura', 'Delta Dunarii', 'ecologie', 'sport'], false, 'Contributie 300 lei', 'https://rowmania.ro/', 'rowmania.ro', 'usor', 'approved', '2026-04-12'),

('Tabara de Stiinta si Astronomie -- Bran 2026', 'Tabara de vara dedicata pasionatilor de stiinta si astronomie. Observatii cu telescop, experimente de fizica, workshop-uri de astrofotografie. Locatie: zona Bran-Moeciu, Brasov.', 'tabere', 'Societatea Romana de Astronomie', 'Bran-Moeciu, Brasov', 'August 2026', '15 Iulie 2026', '14-19 ani', ARRAY['astronomie', 'stiinta', 'natura', 'cercetare'], false, 'Contributie 500 lei', 'https://www.astro.ro/', 'astro.ro', 'mediu', 'approved', '2026-04-12'),

-- === BURSE NOI ===
('Active Citizens Fund Romania -- Granturi pentru ONG-uri de Tineret', 'Finantari pentru organizatii care dezvolta proiecte de tineret, cetatenie activa si drepturile omului. Granturi intre 10.000-200.000 EUR. Sustinut de Norvegia, Islanda si Liechtenstein.', 'burse', 'Active Citizens Fund / FDSC', 'Romania', 'Apeluri periodice 2026', NULL, '18+ ani', ARRAY['granturi', 'ONG', 'cetatenie activa', 'finantare'], true, NULL, 'https://activecitizensfund.ro/', 'activecitizensfund.ro', 'avansat', 'approved', '2026-04-12'),

('FRDS -- Fondul Social European pentru Tineri NEET', 'Fondul Roman de Dezvoltare Sociala ofera programe pentru tineri NEET (Not in Education, Employment or Training). Cursuri gratuite de calificare, consiliere profesionala, stagii platite si sprijin pentru antreprenoriat.', 'burse', 'FRDS - Fondul Roman de Dezvoltare Sociala', 'National', 'Program continuu 2026', NULL, '16-29 ani', ARRAY['NEET', 'calificare', 'angajare', 'educatie'], true, NULL, 'https://www.frfrds.ro/', 'frds.ro', 'mediu', 'approved', '2026-04-12'),

('BursaDeStudiu.ro -- Agregator Burse Nationale si Internationale', 'Platforma cu peste 120 de burse disponibile pentru elevi si studenti romani. Burse de merit, sociale, pentru studii in strainatate, cercetare si stagii. Actualizare saptamanala.', 'burse', 'BursaDeStudiu.ro', 'Romania + International', 'Inscrieri tot anul', NULL, '14-30 ani', ARRAY['bursa', 'studii', 'strainatate', 'merit'], true, NULL, 'https://bursadestudiu.ro/', 'bursadestudiu.ro', 'mediu', 'approved', '2026-04-12');
