-- =============================================================
-- DirecțiaTa — 50 Companii Internship (seed data)
-- Status: approved, deadline: 3 luni de la inserare
-- Rulează în Supabase SQL Editor DUPĂ supabase-practica.sql
-- =============================================================

INSERT INTO internships (
  company_name, company_website, company_email,
  title, description, domain,
  location, work_type, duration, schedule, spots,
  requirements, benefits, is_paid, salary_info,
  deadline, status, is_featured
) VALUES

-- ===================== IT & PROGRAMARE (15) =====================

('Microsoft Romania', 'https://careers.microsoft.com', 'hr@microsoft.com',
 'Software Engineering Internship',
 'Alătură-te echipei Microsoft România într-un program de internship de vară. Vei lucra pe proiecte reale în echipe de dezvoltare, vei primi mentorat din partea inginerilor seniori și vei contribui la produse utilizate de milioane de oameni.',
 'IT & Programare',
 'București', 'hybrid', '3 luni', 'Full-time', 10,
 'Student la Informatică, Calculatoare sau domeniu similar. Cunoștințe de programare (C#, Python, Java). Engleză fluent.',
 'Salariu competitiv, mentorat, posibilitate de angajare full-time, acces la tehnologii de ultimă generație.',
 true, 'Competitiv (nedivulgat)',
 CURRENT_DATE + INTERVAL '3 months', 'approved', true),

('Google Romania', 'https://careers.google.com', 'hr@google.com',
 'STEP / Software Engineering Intern',
 'Programul STEP (Student Training in Engineering Program) este destinat studenților în primii ani de facultate. Vei lucra pe proiecte Google reale sub îndrumarea unui mentor dedicat.',
 'IT & Programare',
 'București', 'on-site', '12 săptămâni', 'Full-time', 5,
 'Student anul I-II la Informatică sau Calculatoare. Cunoștințe de bază în algoritmi și structuri de date.',
 'Salariu atractiv, masă gratuită la birou, mentorat, networking global, posibilitate de return offer.',
 true, 'Competitiv (nedivulgat)',
 CURRENT_DATE + INTERVAL '3 months', 'approved', true),

('Amazon Development Center', 'https://www.amazon.jobs', 'hr@amazon.com',
 'Software Development Engineer Intern',
 'La Amazon Development Center din București sau Iași vei lucra în echipe Agile pe servicii cloud (AWS), machine learning sau e-commerce. Fiecare intern primește un proiect real cu impact.',
 'IT & Programare',
 'București, Iași', 'on-site', '3 luni', 'Full-time', 15,
 'Student la Informatică/Calculatoare, anul II+. Java, Python sau C++. Cunoștințe OOP și algoritmi.',
 'Salariu foarte bun, relocare dacă e cazul, mentorat, posibilitate de angajare.',
 true, 'Competitiv (nedivulgat)',
 CURRENT_DATE + INTERVAL '3 months', 'approved', true),

('IBM Romania', 'https://www.ibm.com/ro-ro', 'hr@ibm.com',
 'IBM Internship — Cloud & AI',
 'Internship în echipele IBM de Cloud Computing și Inteligență Artificială. Vei aplica tehnologii moderne (Watson, Cloud Pak) și vei contribui la soluții enterprise.',
 'IT & Programare',
 'București', 'hybrid', '3 luni', 'Full-time', 8,
 'Student la Informatică, anul II+. Interes pentru cloud computing sau AI/ML. Engleză B2+.',
 'Salariu, certificări IBM gratuite, mentorat, program flexibil.',
 true, '3000-4000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Oracle Romania', 'https://www.oracle.com/ro/', 'hr@oracle.com',
 'Oracle Summer Internship',
 'Program de vară în echipele Oracle de dezvoltare software. Vei lucra pe Oracle Cloud Infrastructure, baze de date sau aplicații enterprise într-un mediu internațional.',
 'IT & Programare',
 'București', 'hybrid', '3 luni', 'Full-time', 12,
 'Student la Informatică sau Calculatoare. Java, SQL, Linux. Engleză fluent.',
 'Salariu competitiv, training-uri Oracle, mentorat, team buildings.',
 true, '3500-5000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Endava', 'https://www.endava.com', 'hr@endava.com',
 'Endava Internship Program',
 'Program de internship în development, QA sau DevOps. Vei fi integrat într-o echipă de proiect reală și vei lucra cu tehnologii moderne (React, .NET, AWS).',
 'IT & Programare',
 'București, Cluj-Napoca, Iași', 'hybrid', '3 luni', 'Full-time', 20,
 'Student anul II+ la Informatică. Cunoștințe de bază într-un limbaj de programare.',
 'Salariu, mentorat, training-uri tehnice, posibilitate de angajare.',
 true, '3000-3500 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('UiPath', 'https://www.uipath.com', 'hr@uipath.com',
 'UiPath Summer Engineering Intern',
 'Fii parte din echipa unicornului românesc! Vei lucra pe platforma de automatizare RPA, contribuind la funcționalități noi sau îmbunătățiri ale produselor existente.',
 'IT & Programare',
 'București, Cluj-Napoca', 'hybrid', '3 luni', 'Full-time', 10,
 'Student la Informatică/Calculatoare. C#, .NET sau Python. Pasiune pentru automatizare.',
 'Salariu atractiv, acces la platformă UiPath, mentorat, cultura startup.',
 true, 'Competitiv (nedivulgat)',
 CURRENT_DATE + INTERVAL '3 months', 'approved', true),

('Bitdefender', 'https://www.bitdefender.com', 'hr@bitdefender.com',
 'Bitdefender Security Internship',
 'Internship în cybersecurity la una dintre cele mai mari companii de securitate din lume. Vei lucra pe detecție malware, machine learning aplicat sau dezvoltare produs.',
 'IT & Programare',
 'București, Iași, Cluj-Napoca, Timișoara', 'on-site', '3 luni', 'Full-time', 15,
 'Student la Informatică. C/C++, Python. Interes pentru securitate cibernetică.',
 'Salariu, training în securitate, mentorat de la cercetători, posibilitate de angajare.',
 true, '3000-4000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', true),

('Continental Automotive', 'https://www.continental.com/ro-ro/', 'hr@continental.com',
 'Continental IT & Engineering Internship',
 'Practică în dezvoltare software automotive, embedded systems sau AI/ML pentru condus autonom. Continental oferă unul dintre cele mai mari programe de internship din România.',
 'IT & Programare',
 'Timișoara, Sibiu, Iași, Cluj-Napoca', 'on-site', '3-6 luni', 'Full-time / Part-time', 30,
 'Student la Informatică, Electronică sau Automatică. C/C++, Python. Permis auto este un plus.',
 'Salariu, transport asigurat, cantină, mentorat, program flexibil pt studenți.',
 true, '2500-3500 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('NTT DATA Romania', 'https://www.nttdata.com/ro', 'hr@nttdata.com',
 'NTT DATA Academy — Java / .NET',
 'Program de academie și internship combinat. Primele 4 săptămâni sunt de training intensiv (Java sau .NET), urmate de 2 luni pe proiect real.',
 'IT & Programare',
 'Cluj-Napoca, București', 'hybrid', '3 luni', 'Full-time', 20,
 'Student la Informatică sau Calculatoare, anul II+. Cunoștințe de bază de programare.',
 'Salariu din prima zi, training plătit, certificare, mentorat, angajare la final de program.',
 true, '2500-3000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Atos Romania', 'https://atos.net/ro/romania', 'hr@atos.net',
 'Atos IT Internship',
 'Internship în cloud computing, cybersecurity sau dezvoltare aplicații. Vei lucra cu echipe internaționale pe proiecte din multiple industrii.',
 'IT & Programare',
 'Timișoara, București', 'hybrid', '3 luni', 'Full-time', 10,
 'Student la Informatică. Cunoștințe într-un limbaj de programare. Engleză B2+.',
 'Salariu, certificări cloud, mentorat, posibilitate de angajare.',
 true, '2500-3000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Cognizant Softvision', 'https://www.cognizantsoftvision.com', 'hr@softvision.com',
 'Softvision Academy — Full Stack',
 'Academie de dezvoltare full-stack (React + Node.js/Java). Primele săptămâni de training, apoi integrare pe proiect. Program conceput special pentru studenți.',
 'IT & Programare',
 'Cluj-Napoca, Timișoara, Iași', 'hybrid', '3 luni', 'Full-time', 25,
 'Student la Informatică, anul II+. HTML/CSS/JS de bază. Dorință de învățare.',
 'Salariu, training plătit, echipament de lucru, posibilitate de angajare.',
 true, '2500-3000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Accenture Romania', 'https://www.accenture.com/ro-ro', 'hr@accenture.com',
 'Accenture Technology Internship',
 'Internship în consultanță IT, dezvoltare software sau analiză de date într-o companie globală. Proiecte pentru clienți din banking, telecom, retail.',
 'IT & Programare',
 'București, Cluj-Napoca, Timișoara', 'hybrid', '3 luni', 'Full-time', 15,
 'Student la Informatică, Matematică sau Economie. Gândire analitică. Engleză fluent.',
 'Salariu, training Accenture, networking internațional, mentorat, transport.',
 true, '3000-4000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Siemens Romania', 'https://www.siemens.com/ro', 'hr@siemens.com',
 'Siemens Student Internship — Software',
 'Practică în dezvoltare software pentru automatizare industrială, IoT sau digital twin. Proiecte cu impact real în fabrici și infrastructură.',
 'IT & Programare',
 'București, Sibiu', 'on-site', '3 luni', 'Full-time', 8,
 'Student la Informatică, Automatică sau Electronică. Python, C++. Interes pentru industrie 4.0.',
 'Salariu, acces la tehnologii Siemens, mentorat, vizite în fabrici.',
 true, '3000-3500 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Bosch Romania', 'https://www.bosch.ro', 'hr@bosch.com',
 'Bosch Engineering & IT Internship',
 'Internship în echipele de R&D Bosch: embedded software, computer vision, testare automatizată sau project management tehnic.',
 'IT & Programare',
 'Cluj-Napoca, București', 'on-site', '3-6 luni', 'Full-time / Part-time', 12,
 'Student la Informatică, Electronică sau Mecanică. C/C++, Python. Germana este un plus.',
 'Salariu, cantină, transport, mentorat, posibilitate de teză de licență.',
 true, '2500-3500 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

-- ===================== FINANȚE & BĂNCI (8) =====================

('Banca Transilvania', 'https://www.bancatransilvania.ro', 'hr@bancatransilvania.ro',
 'BT Internship — Digital Banking',
 'Internship în cea mai mare bancă din România. Vei lucra în echipele de digital banking, analiză de date sau marketing, contribuind la digitalizarea serviciilor bancare.',
 'Finanțe',
 'Cluj-Napoca', 'on-site', '3 luni', 'Full-time', 10,
 'Student la Economie, Informatică sau Matematică, anul II+. Excel, gândire analitică.',
 'Salariu, mentorat, networking, posibilitate de angajare, card BT Bonus.',
 true, '2500-3000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', true),

('BCR (Erste Group)', 'https://www.bcr.ro', 'hr@bcr.ro',
 'BCR Internship Program',
 'Program de internship în banking: retail, corporate, risk, IT sau marketing. BCR face parte din Erste Group și oferă expunere internațională.',
 'Finanțe',
 'București', 'hybrid', '3 luni', 'Full-time', 12,
 'Student la Economie, Finanțe sau Informatică, anul II+. Engleză B2+.',
 'Salariu, training în banking, mentorat, team building, posibilitate de angajare.',
 true, '2500-3000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('BRD - Groupe Société Générale', 'https://www.brd.ro', 'hr@brd.ro',
 'BRD Summer Internship',
 'Program estival de internship în echipele BRD: finanțe corporative, retail banking, treasury, IT sau compliance. Expunere la grupul Société Générale.',
 'Finanțe',
 'București', 'on-site', '2 luni', 'Full-time', 8,
 'Student la Economie sau Finanțe, anul II+. Engleză și/sau franceză. Excel avansat.',
 'Salariu, training, mentorat, networking în grupul SocGen.',
 true, '2500-3000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('ING Bank Romania', 'https://www.ing.ro', 'hr@ing.ro',
 'ING Internship — Tech & Business',
 'Internship la ING: data analytics, software development, product management sau marketing digital. ING este lider în digital banking.',
 'Finanțe',
 'București', 'hybrid', '3 luni', 'Full-time', 10,
 'Student la Informatică, Economie sau Matematică. Gândire analitică, curiozitate, engleză fluent.',
 'Salariu competitiv, laptop, program flexibil, mentorat, Innovation Bootcamp.',
 true, '3000-4000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Raiffeisen Bank', 'https://www.raiffeisen.ro', 'hr@raiffeisen.ro',
 'Raiffeisen Internship Program',
 'Program structurat de internship cu rotație pe departamente: risc, retail, corporate, IT. Include workshop-uri de dezvoltare personală.',
 'Finanțe',
 'București', 'hybrid', '3 luni', 'Full-time', 10,
 'Student la Economie, Finanțe sau IT, anul III+. Engleză B2+. Excel.',
 'Salariu, training, mentorat, team building, certificat de practică.',
 true, '2500-3000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Deloitte Romania', 'https://www2.deloitte.com/ro', 'hr@deloitte.com',
 'Deloitte Internship — Audit & Consulting',
 'Internship în echipele de audit, consultanță, tax sau financial advisory la una din cele mai mari firme Big 4. Training intensiv + proiecte reale la clienți.',
 'Finanțe',
 'București, Cluj-Napoca, Timișoara', 'hybrid', '3 luni', 'Full-time', 20,
 'Student la Economie, Finanțe, Drept sau Informatică, anul II+. Engleză fluent. Excel.',
 'Salariu, certificări (ACCA), mentorat, networking Big4, posibilitate de angajare.',
 true, '3000-4000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', true),

('PwC Romania', 'https://www.pwc.ro', 'hr@pwc.com',
 'PwC Internship — Assurance & Advisory',
 'Program de internship la PwC în audit, tax, consultanță sau deals. Vei lucra cu clienți din diverse industrii și vei primi training intensiv.',
 'Finanțe',
 'București, Cluj-Napoca, Timișoara', 'hybrid', '3 luni', 'Full-time', 15,
 'Student la Economie, Finanțe sau Drept, anul III+. Engleză fluent. Abilități analitice.',
 'Salariu, training PwC Academy, mentorat, networking, posibilitate de contract.',
 true, '3000-3500 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('EY Romania', 'https://www.ey.com/ro', 'hr@ey.com',
 'EY Internship — Audit HUB Team',
 'Internship flexibil în echipa HUB de audit EY. Vei contribui la proiecte de audit financiar pentru companii multinaționale, cu program adaptat studenților.',
 'Finanțe',
 'București, Cluj-Napoca, Iași, Timișoara', 'hybrid', '3 luni', 'Full-time / Part-time', 15,
 'Student la Economie sau Finanțe, anul II+. Engleză B2+. Atenție la detalii.',
 'Salariu, training EY, mentorat, networking global, certificat.',
 true, '2500-3500 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

-- ===================== FMCG & RETAIL (8) =====================

('Procter & Gamble Romania', 'https://www.pgcareers.com', 'hr@pg.com',
 'P&G Internship — Marketing & Sales',
 'Internship la P&G în marketing, vânzări sau supply chain. Vei gestiona branduri cunoscute (Ariel, Gillette, Pampers) și vei lua decizii reale de business.',
 'Marketing',
 'București', 'on-site', '3 luni', 'Full-time', 8,
 'Student la Economie, Marketing sau Business, anul II+. Engleză fluent. Leadership.',
 'Salariu atractiv, training P&G, mentorat, responsabilitate reală pe brand.',
 true, 'Competitiv (nedivulgat)',
 CURRENT_DATE + INTERVAL '3 months', 'approved', true),

('Unilever South Central Europe', 'https://careers.unilever.com', 'hr@unilever.com',
 'Unilever Future Leaders Internship',
 'Program de internship în marketing, supply chain, finanțe sau HR. Unilever caută viitorii lideri prin proiecte cu impact real pe branduri globale.',
 'Marketing',
 'București', 'hybrid', '3 luni', 'Full-time', 6,
 'Student la Business, Marketing sau Economie, anul III+. Engleză fluent. Spirit de lider.',
 'Salariu, training global Unilever, mentorat, posibilitate Future Leaders Programme.',
 true, 'Competitiv (nedivulgat)',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Coca-Cola HBC Romania', 'https://careers.coca-colahellenic.com', 'hr@cchellenic.com',
 'Coca-Cola HBC Management Trainee / Internship',
 'Internship în marketing, vânzări, finanțe sau supply chain la Coca-Cola HBC. Program structurat cu rotație și proiect final prezentat managementului.',
 'Marketing',
 'București', 'on-site', '3 luni', 'Full-time', 8,
 'Student la Economie, Marketing sau Inginerie, anul II+. Engleză B2+. Dinamism.',
 'Salariu, transport, training, mentorat, vizite în fabrică, networking.',
 true, '2500-3500 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Nestlé Romania', 'https://www.nestle.ro', 'hr@nestle.com',
 'Nestlé Internship — Marketing & Supply Chain',
 'Practică la Nestlé pe branduri precum Nescafé, KitKat sau Maggi. Vei participa la campanii de marketing, analize de piață și proiecte de inovație.',
 'Marketing',
 'București', 'hybrid', '3 luni', 'Full-time', 5,
 'Student la Marketing, Business sau Nutriție, anul II+. Engleză fluent. Creativitate.',
 'Salariu, produse Nestlé, training, mentorat, posibilitate de angajare.',
 true, '2500-3000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('PepsiCo Romania', 'https://www.pepsico.com', 'hr@pepsico.com',
 'PepsiCo Dare To Do More Internship',
 'Program de internship în sales, marketing, finanțe sau supply chain. PepsiCo oferă responsabilitate reală și un program de dezvoltare accelerat.',
 'Marketing',
 'București', 'hybrid', '3 luni', 'Full-time', 8,
 'Student la Business, Marketing sau Inginerie, anul II+. Engleză B2+. Ambiție.',
 'Salariu, training PepsiCo, mentorat, team building, produse gratuite.',
 true, '2500-3500 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Lidl Romania', 'https://cariere.lidl.ro', 'hr@lidl.ro',
 'Lidl Internship — Store Management & Logistics',
 'Internship în managementul magazinelor, logistică, achiziții sau marketing la Lidl. Program structurat cu rotație între departamente.',
 'Marketing',
 'București + național', 'on-site', '3 luni', 'Full-time', 15,
 'Student la Business, Economie sau Inginerie, anul II+. Română nativă. Disponibilitate deplasare.',
 'Salariu peste medie, masă gratuită, training intensiv, posibilitate de angajare.',
 true, '3000-4000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Kaufland Romania', 'https://cariere.kaufland.ro', 'hr@kaufland.ro',
 'Kaufland Internship Program',
 'Internship la Kaufland în achiziții, marketing, IT, logistică sau real estate. Program cu rotație și proiect individual evaluat de management.',
 'Marketing',
 'București + național', 'on-site', '3 luni', 'Full-time', 12,
 'Student la Economie, Marketing sau Inginerie, anul II+. Română. Germana este un plus.',
 'Salariu, masă, training, mentorat, vizite în centre logistice.',
 true, '2500-3500 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('eMAG', 'https://www.emag.ro', 'hr@emag.ro',
 'eMAG Internship — IT & Business',
 'Internship la cel mai mare retailer online din România. Poziții în dezvoltare web, data science, product management, marketing digital sau logistică.',
 'IT & Programare',
 'București', 'hybrid', '3 luni', 'Full-time', 15,
 'Student la Informatică, Economie sau Marketing, anul II+. Curiozitate și inițiativă.',
 'Salariu, discount eMAG, training, mentorat, posibilitate de angajare, birou modern.',
 true, '3000-4000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', true),

-- ===================== ENERGIE & INDUSTRIE (7) =====================

('OMV Petrom', 'https://www.omvpetrom.com', 'hr@petrom.com',
 'OMV Petrom Internship — Engineering & Business',
 'Internship la cea mai mare companie din România. Poziții în inginerie (upstream, downstream, energie), finanțe, IT sau resurse umane.',
 'Inginerie',
 'București', 'on-site', '3 luni', 'Full-time', 20,
 'Student la Petrol & Gaze, Inginerie, Chimie, Economie sau IT, anul II+. Engleză fluent.',
 'Salariu atractiv, transport, cantină, mentorat, vizite pe platforma, posibilitate angajare.',
 true, '3500-5000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', true),

('E.ON Romania', 'https://www.eon.ro', 'hr@eon.ro',
 'E.ON Internship — Energie & Digitalizare',
 'Practică la E.ON în energie, digitalizare, rețele electrice sau relații cu clienții. E.ON este unul dintre cei mai mari furnizori de energie din România.',
 'Inginerie',
 'Târgu Mureș, Iași', 'on-site', '3 luni', 'Full-time', 10,
 'Student la Energetică, Electronică sau Informatică, anul II+. Cunoștințe tehnice de bază.',
 'Salariu, training, mentorat, vizite în substații, certificat de practică.',
 true, '2500-3000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Delgaz Grid (E.ON)', 'https://www.delgaz-grid.ro', 'hr@delgaz-grid.ro',
 'Delgaz Grid Trainee Program',
 'Program trainee în distribuția de gaze și electricitate. Vei lucra pe proiecte de mentenanță, modernizare rețele și digitalizare operațiuni.',
 'Inginerie',
 'Târgu Mureș', 'on-site', '6 luni', 'Full-time', 8,
 'Student la Energetică, Instalații sau Inginerie, anul III+. Disponibilitate deplasare teren.',
 'Salariu, echipament de protecție, training tehnic, mentorat, posibilitate de angajare.',
 true, '2500-3000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Distribuție Energie Oltenia', 'https://www.distributieoltenia.ro', 'hr@distributieoltenia.ro',
 'DEOE Internship — Specialist Relații Utilizatori',
 'Practică în relațiile cu clienții și managementul rețelelor electrice. Ideal pentru studenți la energetică sau economie în zona Olteniei.',
 'Inginerie',
 'Craiova, Târgu Jiu', 'on-site', '2 luni', 'Full-time', 5,
 'Student la Energetică sau Economie, anul II+. Abilități de comunicare.',
 'Salariu, training, mentorat, certificat de practică, posibilitate de angajare.',
 false, NULL,
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Romgaz', 'https://www.romgaz.ro', 'hr@romgaz.ro',
 'Romgaz — Practică pentru Studenți',
 'Practică de vară la cel mai mare producător de gaze din România. Domenii: explorare, producție, inginerie de zăcământ, economie.',
 'Inginerie',
 'Mediaș', 'on-site', '1-2 luni', 'Full-time', 10,
 'Student la Petrol & Gaze, Geologie, Inginerie sau Economie. Disponibilitate în Mediaș.',
 'Indemnizație, transport, cantină, mentorat, vizite pe sonde.',
 false, 'Indemnizație de practică',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Nuclearelectrica', 'https://www.nuclearelectrica.ro', 'hr@nuclearelectrica.ro',
 'Nuclearelectrica Internship — Inginerie Nucleară',
 'Practică la Centrala Nucleară de la Cernavodă. Program unic în România pentru studenții interesați de energia nucleară.',
 'Inginerie',
 'București, Cernavodă', 'on-site', '2 luni', 'Full-time', 5,
 'Student la Inginerie Nucleară, Energetică sau Fizică, anul III+. Atestat de securitate.',
 'Salariu, transport Cernavodă, cazare, training de securitate nucleară, vizită în centrală.',
 true, '3000-4000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Schneider Electric Romania', 'https://www.se.com/ro', 'hr@se.com',
 'Schneider Electric Internship',
 'Internship în automatizări industriale, managementul energiei sau dezvoltare software pentru soluții IoT. Mediu internațional și inovator.',
 'Inginerie',
 'București', 'hybrid', '3 luni', 'Full-time', 6,
 'Student la Automatică, Electronică sau Informatică, anul II+. Engleză B2+.',
 'Salariu, training Schneider, mentorat, certificări, posibilitate de angajare.',
 true, '2500-3500 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

-- ===================== TELECOM & MEDIA (5) =====================

('Orange Romania', 'https://www.orange.ro', 'hr@orange.ro',
 'Orange Summer Practice',
 'Cel mai mare program de practică din telecom. Poziții în marketing digital, data analytics, rețele, customer experience sau dezvoltare aplicații.',
 'IT & Programare',
 'București', 'hybrid', '2 luni', 'Full-time', 20,
 'Student la Informatică, Telecomunicații, Marketing sau Economie, anul II+. Engleză.',
 'Salariu, acces la Orange Fab, mentorat, hackathon intern, networking.',
 true, '2500-3000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Vodafone Romania', 'https://www.vodafone.ro', 'hr@vodafone.ro',
 'Vodafone Discover Program — Internship',
 'Program Discover de internship la Vodafone: tech, marketing, finanțe sau customer operations. Include sesiuni de coaching și prezentare finală.',
 'IT & Programare',
 'București', 'hybrid', '3 luni', 'Full-time', 15,
 'Student la Informatică, Economie sau Marketing, anul II+. Engleză fluent. Curiozitate.',
 'Salariu, coaching, training Vodafone Academy, team building, posibilitate de angajare.',
 true, '3000-3500 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Ericsson Romania', 'https://www.ericsson.com/ro', 'hr@ericsson.com',
 'Ericsson Internship — 5G & Cloud',
 'Internship la Ericsson în echipele de 5G, cloud infrastructure sau AI/ML. Vei contribui la dezvoltarea rețelelor mobile de următoare generație.',
 'IT & Programare',
 'București', 'on-site', '3 luni', 'Full-time', 6,
 'Student la Electronică, Telecomunicații sau Informatică, anul III+. C++, Python. Engleză.',
 'Salariu, acces la laboratoare 5G, mentorat, training, posibilitate de teză.',
 true, '3000-4000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Nokia Romania', 'https://www.nokia.com', 'hr@nokia.com',
 'Nokia Summer Trainee — R&D',
 'Practică de vară în echipele de R&D Nokia din Timișoara. Focus pe networking, software-defined networks, automatizare și testare.',
 'IT & Programare',
 'Timișoara', 'on-site', '3 luni', 'Full-time', 8,
 'Student la Informatică, Electronică sau Telecomunicații, anul II+. Python, Linux. Engleză.',
 'Salariu, mentorat de la ingineri seniori, training tehnic, networking internațional.',
 true, '3000-3500 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Samsung Romania', 'https://www.samsung.com/ro/', 'hr@samsung.com',
 'Samsung Internship — R&D Software',
 'Internship în echipa Samsung R&D din București. Proiecte pe Tizen OS, AI/ML, computer vision sau dezvoltare mobile.',
 'IT & Programare',
 'București', 'on-site', '3 luni', 'Full-time', 5,
 'Student la Informatică sau Electronică, anul III+. C/C++, Java sau Python. Algoritmi.',
 'Salariu, echipamente Samsung, mentorat, training tehnic, posibilitate de angajare.',
 true, '3500-4500 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

-- ===================== FARMA & SĂNĂTATE (4) =====================

('GSK Romania', 'https://www.gsk.com/ro-ro/', 'hr@gsk.com',
 'GSK Internship — Industrial & QA',
 'Practică la fabrica GSK din Brașov în producție farmaceutică, quality assurance, supply chain sau inginerie industrială.',
 'Sănătate',
 'Brașov', 'on-site', '3 luni', 'Full-time', 5,
 'Student la Farmacie, Chimie, Inginerie Chimică sau Biologie, anul III+. Engleză B2+.',
 'Salariu, training GMP, mentorat, vizite în laborator, posibilitate de angajare.',
 true, '2500-3000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Johnson & Johnson Romania', 'https://www.jnj.com', 'hr@jnj.com',
 'J&J Internship — Medical Devices',
 'Internship în medical devices, marketing farma sau compliance la Johnson & Johnson. Expunere la industria medicală într-un mediu internațional.',
 'Sănătate',
 'București', 'hybrid', '3 luni', 'Full-time', 4,
 'Student la Medicină, Farmacie, Biomedical sau Marketing, anul III+. Engleză fluent.',
 'Salariu, training J&J, mentorat, networking global, certificat.',
 true, '3000-3500 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Sanofi Romania', 'https://www.sanofi.ro', 'hr@sanofi.com',
 'Sanofi Industrial Internship',
 'Practică în producția de medicamente, quality control, analiză chimică sau logistică farmaceutică la fabrica Sanofi.',
 'Sănătate',
 'București', 'on-site', '2-3 luni', 'Full-time', 4,
 'Student la Farmacie, Chimie sau Biologie, anul III+. Cunoștințe de laborator. Franceză este un plus.',
 'Salariu, training GMP, mentorat, vizite în laborator, certificat de practică.',
 true, '2500-3000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Pfizer Romania', 'https://www.pfizer.ro', 'hr@pfizer.com',
 'Pfizer Medical Education Internship',
 'Internship în departamentul de medical affairs, clinical research sau medical education la Pfizer. Ideal pentru studenți la medicină sau farmacie.',
 'Sănătate',
 'București', 'hybrid', '3 luni', 'Full-time', 3,
 'Student la Medicină sau Farmacie, anul IV+. Engleză fluent. Interes pentru cercetare.',
 'Salariu, training medical, mentorat, acces la conferințe, networking în industria farma.',
 true, '3000-4000 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

-- ===================== HR, CONSULTANȚĂ & ALTELE (3) =====================

('KPMG Romania', 'https://home.kpmg/ro', 'hr@kpmg.ro',
 'KPMG Internship — Audit & Tax',
 'Internship Big 4 în audit, taxe, consultanță sau deal advisory. Program structurat cu training, proiecte reale la clienți și evaluare finală.',
 'Finanțe',
 'București', 'hybrid', '3 luni', 'Full-time', 12,
 'Student la Economie, Finanțe sau Drept, anul II+. Engleză fluent. Excel. Gândire analitică.',
 'Salariu, training KPMG, studii ACCA suportate, mentorat, networking Big4.',
 true, '3000-3500 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('McDonald''s Romania (Premier Restaurants)', 'https://www.mcdonalds.ro', 'hr@mcdonalds.ro',
 'YoungLead — Program de Dezvoltare McDonald''s',
 'Program intensiv de management și leadership în restaurante McDonald''s. Vei trece prin toate pozițiile și vei învăța managementul operațional.',
 'HR',
 'Nacional', 'on-site', '3-6 luni', 'Full-time / Part-time', 50,
 'Student sau absolvent. Fără experiență necesară. Disponibilitate pentru lucru în ture.',
 'Salariu, masă gratuită, uniformă, training intensiv, carieră rapidă în management.',
 true, '2500-3500 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false),

('Interbrands Orbico', 'https://www.orbico.com', 'hr@orbico.ro',
 'Orbico Internship — Supply Chain & Sales',
 'Internship la cel mai mare distribuitor din Europa Centrală și de Est. Poziții în supply chain, vânzări, logistică sau marketing trade.',
 'Marketing',
 'București', 'on-site', '3 luni', 'Full-time', 8,
 'Student la Economie, Logistică sau Marketing, anul II+. Abilități organizatorice.',
 'Salariu, training, mentorat, vizite în depozite, posibilitate de angajare.',
 true, '2000-2500 RON/lună',
 CURRENT_DATE + INTERVAL '3 months', 'approved', false);

-- Verificare:
SELECT domain, COUNT(*) as nr FROM internships WHERE status = 'approved' GROUP BY domain ORDER BY nr DESC;
