-- ================================================
-- DirecțiaTa -- Completare la 101 oportunități
-- Rulează acest SQL în Supabase SQL Editor
-- Avem deja 35 in DB, adăugăm 66 noi
-- ================================================

INSERT INTO opportunities (title, description, category, organization, location, date, deadline, age_range, tags, is_free, price, url, source, difficulty, status, created_at) VALUES

-- ============================================================
-- BATCH 1: Din supabase-new-opportunities.sql (25 noi)
-- ============================================================

-- === VOLUNTARIAT (8) ===
('SOS Satul Copiilor -- Voluntar Mentor', 'Devino mentor in programele SOS Satele Copiilor Romania. Sprijina copii si tineri care cresc fara parinti prin activitati educationale, recreative si de dezvoltare personala. Training gratuit, supervizare continua.', 'voluntariat', 'SOS Satele Copiilor Romania', 'Bucuresti, Cluj, Sibiu, Timisoara', 'Program continuu -- inscrieri deschise', NULL, '18+ ani', ARRAY['copii', 'mentorat', 'educatie', 'familie'], true, NULL, 'https://www.sos-satelecopiilor.ro/implica-te/voluntariat/', 'sos-satelecopiilor.ro', 'mediu', 'approved', '2026-04-12'),

('Salvati Copiii Romania -- Voluntar in Programe Nationale', 'Cea mai mare organizatie neguvernamentala dedicata drepturilor copilului din Romania. Voluntariaza in programe de educatie, sanatate, protectie si raspuns la urgente. Peste 5 milioane de copii ajutati anual.', 'voluntariat', 'Salvati Copiii Romania', 'National (30+ centre)', 'Program continuu', NULL, '16+ ani', ARRAY['copii', 'drepturi', 'educatie', 'protectie'], true, NULL, 'https://www.salvaticopiii.ro/implica-te/voluntariat', 'salvaticopiii.ro', 'ușor', 'approved', '2026-04-12'),

('AIESEC Romania -- Voluntariat International', 'AIESEC este cea mai mare organizatie de tineret din lume. Participa la proiecte de voluntariat international in peste 120 de tari si regiuni. Dezvoltare de leadership, schimb intercultural, impact social measurabil.', 'voluntariat', 'AIESEC Romania', 'International (120+ tari)', 'Proiecte pe tot parcursul anului', NULL, '18-30 ani', ARRAY['international', 'leadership', 'tineret', 'calatorii'], true, NULL, 'https://aiesec.ro/', 'aiesec.ro', 'mediu', 'approved', '2026-04-12'),

('Greenpeace Romania -- Voluntar Activ', 'Alatura-te comunitatii de voluntari Greenpeace Romania. Campanii pentru protectia padurilor, reducerea poluarii, energie curata si protejarea biodiversitatii. Actiuni de strada, petitii, flash mob-uri si educatie ecologica.', 'voluntariat', 'Greenpeace Romania', 'Bucuresti + National', 'Program continuu', NULL, '16+ ani', ARRAY['mediu', 'ecologie', 'activism', 'paduri'], true, NULL, 'https://www.greenpeace.org/romania/implica-te/', 'greenpeace.org/romania', 'ușor', 'approved', '2026-04-12'),

('WWF Romania -- Voluntar pentru Natura', 'Programul de voluntariat WWF Romania: plantat de copaci, curatenie in arii protejate, monitorizare biodiversitate si educatie de mediu. Romania gazduieste 50% din populatia de ursi bruni din UE.', 'voluntariat', 'WWF Romania', 'Arii protejate, Romania', 'Campanii sezoniere', NULL, '16+ ani', ARRAY['natura', 'biodiversitate', 'conservare', 'mediu'], true, NULL, 'https://wwf.ro/implica-te/', 'wwf.ro', 'ușor', 'approved', '2026-04-12'),

('Asociatia Magic -- Voluntar in Spitalele de Copii', 'Asociatia Magic aduce bucurie in spitalele de copii din Romania. Voluntari dresati in terapia prin joaca, animatie si suport emotional. Prezenta in 20+ spitale, peste 20.000 de copii beneficiari anual.', 'voluntariat', 'Asociatia Magic', 'Spitale pediatrice, Romania', 'Program continuu -- training trimestrial', NULL, '18+ ani', ARRAY['sanatate', 'copii', 'spital', 'terapie prin joaca'], true, NULL, 'https://www.asociatiamagic.ro/voluntariat/', 'asociatiamagic.ro', 'mediu', 'approved', '2026-04-12'),

('YMCA Romania -- Voluntariat Comunitar', 'YMCA Romania ofera programe de voluntariat in centre de tineret din 10 orase. Activitati sportive, educationale, culturale si de dezvoltare comunitara. Membru al YMCA Europe cu peste 180 ani de traditie.', 'voluntariat', 'YMCA Romania', '10 orase din Romania', 'Program continuu', NULL, '14+ ani', ARRAY['sport', 'tineret', 'comunitate', 'educatie'], true, NULL, 'https://ymca.ro/voluntariat/', 'ymca.ro', 'ușor', 'approved', '2026-04-12'),

('Daruieste Viata -- Voluntar in Proiecte de Sanatate', 'Asociatia Daruieste Viata a construit primul spital public din donatii in Romania. Voluntariaza in campanii de donare, logistica, comunicare si proiecte comunitare de sanatate.', 'voluntariat', 'Asociatia Daruieste Viata', 'Bucuresti', 'Program continuu', NULL, '18+ ani', ARRAY['sanatate', 'spital', 'donare', 'comunitate'], true, NULL, 'https://www.daruiesteviata.ro/implicate', 'daruiesteviata.ro', 'mediu', 'approved', '2026-04-12'),

-- === EVENIMENTE (5) ===
('iTEC 2026 -- International Teenagers Conference', 'Conferinta internationala pentru adolescenti organizata la Cluj-Napoca. Workshop-uri, talk-uri inspirationale, networking si proiecte creative. Editia a VI-a, participanti din 15 tari.', 'evenimente', 'iTEC Romania', 'Cluj-Napoca', 'Iunie 2026', '15 Mai 2026', '14-19 ani', ARRAY['conferinta', 'international', 'tineret', 'inspiratie'], true, NULL, 'https://itecromania.ro/', 'itecromania.ro', 'ușor', 'approved', '2026-04-12'),

('TEDxYouth Bucharest 2026', 'Eveniment TEDx dedicat tinerilor din Bucuresti. Talk-uri de 18 minute pe teme de inovatie, stiinta, arta si impact social. Atmosfera inspirationala, networking cu lideri si inovatori.', 'evenimente', 'TEDxYouth@Bucharest', 'Bucuresti', 'Octombrie 2026', NULL, '14-25 ani', ARRAY['TEDx', 'inspiratie', 'inovatie', 'stiinta'], false, 'Bilete de la 30 lei', 'https://tedxyouthbucharest.com/', 'tedxyouthbucharest.com', 'ușor', 'approved', '2026-04-12'),

('Noaptea Cercetatorilor 2026', 'Cel mai mare eveniment de popularizare a stiintei din Romania, parte din Noaptea Europeana a Cercetatorilor. Laboratoare deschise, experimente live, intalniri cu cercetatori, in 20+ orase din Romania.', 'evenimente', 'Comisia Europeana / Universitati din Romania', '20+ orase din Romania', '25 Septembrie 2026', NULL, '14+ ani', ARRAY['stiinta', 'cercetare', 'experimente', 'universitate'], true, NULL, 'https://noapteacercetatorilor.ro/', 'noapteacercetatorilor.ro', 'ușor', 'approved', '2026-04-12'),

('Code for Romania -- Civic Hackathon 2026', 'Hackathon civic organizat de Code for Romania. Dezvolta solutii tech pentru probleme reale ale societatii romanesti. Echipe multidisciplinare, mentori din industrie, premii si implementare reala a proiectelor.', 'evenimente', 'Code for Romania', 'Bucuresti + Online', 'Noiembrie 2026', NULL, '16+ ani', ARRAY['hackathon', 'civic tech', 'programare', 'impact social'], true, NULL, 'https://code4.ro/', 'code4.ro', 'mediu', 'approved', '2026-04-12'),

('Festivalul de Film NexT 2026', 'Festival international de film de scurt metraj pentru tineri cineasti. Proiectii, workshop-uri de regie, montaj si scenariu, intalniri cu profesionisti din industrie. Sectiune competitionala dedicata tinerilor sub 25.', 'evenimente', 'NexT Film Festival', 'Bucuresti', 'Mai 2026', NULL, '16+ ani', ARRAY['film', 'arta', 'creativitate', 'festival'], false, 'Bilete de la 15 lei', 'https://nextfilmfestival.ro/', 'nextfilmfestival.ro', 'ușor', 'approved', '2026-04-12'),

-- === WORKSHOPURI (4) ===
('eTwinning Romania -- Ateliere Internationale Online', 'Proiecte educationale internationale prin platforma eTwinning (Erasmus+). Elevi si profesori din 44 de tari colaboreaza in proiecte online de STEM, arte, limbi straine si cetatenie activa. 100% gratuit.', 'workshopuri', 'eTwinning / ANPCDEFP', 'Online', 'An scolar 2026-2027', NULL, '10-19 ani', ARRAY['eTwinning', 'international', 'educatie', 'online'], true, NULL, 'https://etwinning.ro/', 'etwinning.ro', 'ușor', 'approved', '2026-04-12'),

('Junior Achievement -- Compania de Exercitiu', 'Programul educational JA Romania pentru liceeni. Invata sa creezi un business de la 0: plan de afaceri, marketing, finante, management. 30.000+ elevi participanti anual. Competitie nationala + europeana.', 'workshopuri', 'Junior Achievement Romania', 'National (licee din Romania)', 'An scolar 2025-2026', NULL, '15-19 ani', ARRAY['antreprenoriat', 'business', 'educatie', 'competitie'], true, NULL, 'https://www.jaromania.org/programele-ja/compania-de-exercitiu', 'jaromania.org', 'mediu', 'approved', '2026-04-12'),

('ELSA Romania -- Sesiuni de Drepturile Omului pentru Tineri', 'ELSA (European Law Students Association) Romania ofera workshop-uri gratuite de educatie juridica: drepturile omului, cetatenie europeana, acces la justitie. Predate de studenti la drept.', 'workshopuri', 'ELSA Romania', 'Universitati din Romania + Online', 'Program continuu', NULL, '14+ ani', ARRAY['drepturile omului', 'educatie juridica', 'cetatenie', 'UE'], true, NULL, 'https://elsa-romania.org/', 'elsa-romania.org', 'ușor', 'approved', '2026-04-12'),

('Code for Romania -- Tech for Social Good Workshop', 'Workshop-uri lunare organizate de Code for Romania. Invata React, Python, data science, UX/UI design in contextul proiectelor civice. Mentori voluntari din companiile tech de top din Romania.', 'workshopuri', 'Code for Romania', 'Online (Zoom) + Bucuresti', 'Lunar', NULL, '16+ ani', ARRAY['programare', 'civic tech', 'React', 'design'], true, NULL, 'https://code4.ro/ro/implica-te', 'code4.ro', 'mediu', 'approved', '2026-04-12'),

-- === COMPETITII (3) ===
('Olimpiada Nationala de Matematica 2026', 'Competitie de matematica organizata de Ministerul Educatiei. Etape: locala -> judeteana -> nationala -> Lotul Olimpic International (IMO). Subiecte provocatoare, pregatire de elita, promovare academica.', 'competitii', 'Ministerul Educatiei', 'Centre judetene -> Finala Nationala', 'Februarie - Mai 2026', NULL, '14-19 ani', ARRAY['matematica', 'olimpiada', 'algoritmi', 'excelenta'], true, NULL, 'https://edu.ro', 'edu.ro', 'avansat', 'approved', '2026-04-12'),

('Olimpiadele Nationale de Stiinte 2026', 'Olimpiadele nationale de fizica, chimie si biologie. Etape succesive cu subiecte din materia de liceu si materie olimpica. Promoveaza tineri spre loturi internationale si cariere STEM.', 'competitii', 'Ministerul Educatiei', 'National', 'Martie - Mai 2026', NULL, '14-19 ani', ARRAY['stiinta', 'fizica', 'chimie', 'biologie'], true, NULL, 'https://edu.ro', 'edu.ro', 'avansat', 'approved', '2026-04-12'),

('FIRST Tech Challenge Romania 2026', 'Competitie internationala de robotica pentru echipe de liceeni. Design, constructie si programare de roboti care rezolva provocari reale. Calificari la Campionatul Mondial FIRST din SUA.', 'competitii', 'FIRST Romania / Natie prin Educatie', 'National -> International', 'Octombrie 2026 - Aprilie 2027', NULL, '14-18 ani', ARRAY['robotica', 'STEM', 'inginerie', 'international'], true, NULL, 'https://www.firstinspires.org/robotics/ftc', 'natieprineducatie.ro', 'avansat', 'approved', '2026-04-12'),

-- === TABERE (2) ===
('Tabara Internationala de Tineret -- Sulina 2026', 'Tabara internationala de vara la Sulina, in Delta Dunarii. Activitati ecologice, sporturi nautice, observare de pasari, ateliere de fotografie nature, voluntariat in arii protejate.', 'tabere', 'Asociatia Ivan Patzaichin', 'Sulina, Delta Dunarii', 'Iulie 2026', '15 Iunie 2026', '14-25 ani', ARRAY['natura', 'Delta Dunarii', 'ecologie', 'sport'], false, 'Contributie 300 lei', 'https://rowmania.ro/', 'rowmania.ro', 'ușor', 'approved', '2026-04-12'),

('Tabara de Stiinta si Astronomie -- Bran 2026', 'Tabara de vara dedicata pasionatilor de stiinta si astronomie. Observatii cu telescop, experimente de fizica, workshop-uri de astrofotografie. Locatie: zona Bran-Moeciu, Brasov.', 'tabere', 'Societatea Romana de Astronomie', 'Bran-Moeciu, Brasov', 'August 2026', '15 Iulie 2026', '14-19 ani', ARRAY['astronomie', 'stiinta', 'natura', 'cercetare'], false, 'Contributie 500 lei', 'https://www.astro.ro/', 'astro.ro', 'mediu', 'approved', '2026-04-12'),

-- === BURSE (3) ===
('Active Citizens Fund Romania -- Granturi pentru ONG-uri de Tineret', 'Finantari pentru organizatii care dezvolta proiecte de tineret, cetatenie activa si drepturile omului. Granturi intre 10.000-200.000 EUR. Sustinut de Norvegia, Islanda si Liechtenstein.', 'burse', 'Active Citizens Fund / FDSC', 'Romania', 'Apeluri periodice 2026', NULL, '18+ ani', ARRAY['granturi', 'ONG', 'cetatenie activa', 'finantare'], true, NULL, 'https://activecitizensfund.ro/', 'activecitizensfund.ro', 'avansat', 'approved', '2026-04-12'),

('FRDS -- Fondul Social European pentru Tineri NEET', 'Fondul Roman de Dezvoltare Sociala ofera programe pentru tineri NEET (Not in Education, Employment or Training). Cursuri gratuite de calificare, consiliere profesionala, stagii platite si sprijin pentru antreprenoriat.', 'burse', 'FRDS - Fondul Roman de Dezvoltare Sociala', 'National', 'Program continuu 2026', NULL, '16-29 ani', ARRAY['NEET', 'calificare', 'angajare', 'educatie'], true, NULL, 'https://www.frfrds.ro/', 'frds.ro', 'mediu', 'approved', '2026-04-12'),

('BursaDeStudiu.ro -- Agregator Burse Nationale si Internationale', 'Platforma cu peste 120 de burse disponibile pentru elevi si studenti romani. Burse de merit, sociale, pentru studii in strainatate, cercetare si stagii. Actualizare saptamanala.', 'burse', 'BursaDeStudiu.ro', 'Romania + International', 'Inscrieri tot anul', NULL, '14-30 ani', ARRAY['bursa', 'studii', 'strainatate', 'merit'], true, NULL, 'https://bursadestudiu.ro/', 'bursadestudiu.ro', 'mediu', 'approved', '2026-04-12'),

-- ============================================================
-- BATCH 2: 41 oportunități complet noi (36-66)
-- ============================================================

-- === VOLUNTARIAT NOU (8) ===
('MedLife -- Program de Voluntariat Medical', 'MedLife, cel mai mare furnizor privat de servicii medicale din Romania, ofera oportunitati de voluntariat in campanii de screening gratuit, educatie sanitara si sprijin comunitar in zone rurale.', 'voluntariat', 'Fundatia MedLife', 'National (clinici MedLife)', 'Program continuu', NULL, '18+ ani', ARRAY['sanatate', 'medical', 'screening', 'rural'], true, NULL, 'https://www.medlife.ro/fundatia-medlife', 'medlife.ro', 'mediu', 'approved', '2026-04-14'),

('Hospice Casa Sperantei -- Voluntar in Ingrijiri Paliative', 'Cel mai mare furnizor de ingrijiri paliative din Romania. Voluntarii sunt formati profesional in suport emotional si practic pentru pacientii cu boli grave si familiile lor. Program de training 40 ore.', 'voluntariat', 'Hospice Casa Sperantei', 'Brasov, Bucuresti', 'Program continuu -- training biannual', NULL, '18+ ani', ARRAY['sanatate', 'paliativ', 'empatie', 'suport'], true, NULL, 'https://www.hospice.ro/voluntariat/', 'hospice.ro', 'mediu', 'approved', '2026-04-14'),

('Centrul de Voluntariat Cluj -- Platforma Locala', 'Centrul de Voluntariat Cluj-Napoca pune in legatura voluntari cu organizatii din comunitate. Peste 50 de oportunitati active in educatie, mediu, social, cultura si sport. Inscriere simpla online.', 'voluntariat', 'Centrul de Voluntariat Cluj', 'Cluj-Napoca si imprejurimi', 'Program continuu', NULL, '14+ ani', ARRAY['comunitate', 'Cluj', 'local', 'diversitate'], true, NULL, 'https://centruldevoluntariat.ro/', 'centruldevoluntariat.ro', 'ușor', 'approved', '2026-04-14'),

('Fundatia Comunitara Bucuresti -- Voluntar Local', 'Cea mai mare fundatie comunitara din Romania. Voluntariaza in proiecte finantate de FCB: educatie, mediu, sanatate, cultura. Peste 15.000 de donatori si sute de proiecte anuale.', 'voluntariat', 'Fundatia Comunitara Bucuresti', 'Bucuresti si Ilfov', 'Program continuu', NULL, '16+ ani', ARRAY['comunitate', 'Bucuresti', 'donare', 'proiecte locale'], true, NULL, 'https://www.fundatiacomunitarabucuresti.ro/', 'fundatiacomunitarabucuresti.ro', 'ușor', 'approved', '2026-04-14'),

('Voluntar pe Biciclete -- Pedalez pentru Educatie', 'Proiect de voluntariat care combina ciclismul cu educatia. Echipe de tineri pedaleza intre scoli din mediul rural, sustinand ateliere interactive pentru copii. Echipament furnizat.', 'voluntariat', 'Asociatia Pedalez', 'Romania (trasee rurale)', 'Mai - Septembrie 2026', NULL, '18+ ani', ARRAY['ciclism', 'educatie', 'rural', 'sport'], true, NULL, 'https://www.pedalez.ro/', 'pedalez.ro', 'mediu', 'approved', '2026-04-14'),

('Asociatia Zi de Bine -- Voluntar in Campanii Sociale', 'Zi de Bine organizeaza campanii nationale de strangere de fonduri: Trupele lui Mos Craciun, Vara Impreuna si Paste cu Zâmbet. Fii voluntar in logistica, empachetare, livrare si comunicare.', 'voluntariat', 'Asociatia Zi de Bine', 'Bucuresti + National', 'Campanii periodice', NULL, '14+ ani', ARRAY['social', 'campanie', 'cadouri', 'comunitate'], true, NULL, 'https://www.zidebine.ro/', 'zidebine.ro', 'ușor', 'approved', '2026-04-14'),

('OvidiuRo -- Voluntar in Programul Fiecare Copil in Gradinita', 'OvidiuRo lupta pentru accesul copiilor din comunitati marginalizate la educatie prescolara. Voluntarii ajuta in gradinite de vara, distribuie rechizite si sustin familii. Impact in 200+ comunitati.', 'voluntariat', 'Asociatia OvidiuRo', 'Comunitati marginalizate, Romania', 'Vara 2026 + program continuu', NULL, '18+ ani', ARRAY['educatie', 'prescolar', 'incluziune', 'copii'], true, NULL, 'https://ovfreedomidia.ro/', 'ovidiuro.ro', 'mediu', 'approved', '2026-04-14'),

('Plan International Romania -- Voluntar Advocacy', 'Plan International promoveaza drepturile copiilor si egalitatea de gen in Romania. Voluntarii participa in campanii de advocacy, educatie si constientizare. Proiecte in 80+ tari.', 'voluntariat', 'Plan International Romania', 'Bucuresti + Online', 'Program continuu', NULL, '16+ ani', ARRAY['drepturi', 'egalitate', 'advocacy', 'copii'], true, NULL, 'https://plan-international.org/romania/', 'plan-international.org', 'ușor', 'approved', '2026-04-14'),

-- === EVENIMENTE NOI (8) ===
('Zilele Voluntariatului -- 5 Decembrie 2026', 'Saptamana internationala a Voluntariatului, marchata prin evenimente in toata Romania. Gale de premiere, workshop-uri, actiuni comunitare. Organizeaza un eveniment in comunitatea ta!', 'evenimente', 'Diverse organizatii / ONU', 'National', '1-7 Decembrie 2026', NULL, '14+ ani', ARRAY['voluntariat', 'gala', 'comunitate', 'international'], true, NULL, 'https://www.un.org/en/observances/volunteer-day', 'un.org', 'ușor', 'approved', '2026-04-14'),

('Bucharest Science Festival 2026', 'Festival de stiinta populara in Bucuresti. Experimente interactive, show-uri de chimie, robotica, astronomie si inteligenta artificiala. Intrare libera, activitati pentru toate varstele.', 'evenimente', 'ICub / Universitatea Bucuresti', 'Bucuresti', 'Septembrie 2026', NULL, '10+ ani', ARRAY['stiinta', 'festival', 'experimente', 'gratuit'], true, NULL, 'https://www.bucharest-science-festival.ro/', 'bucharest-science-festival.ro', 'ușor', 'approved', '2026-04-14'),

('Europe Day Romania -- 9 Mai 2026', 'Ziua Europei, sarbatorita prin evenimente organizate de Reprezentanta CE in Romania. Festivaluri, expozitii, concerte si dezbateri despre viitorul UE. Intrare libera in toate locatiile.', 'evenimente', 'Reprezentanta CE in Romania', 'Bucuresti + orase universitare', '9 Mai 2026', NULL, '14+ ani', ARRAY['Europa', 'UE', 'festival', 'cetatenie'], true, NULL, 'https://romania.representation.ec.europa.eu/', 'ec.europa.eu', 'ușor', 'approved', '2026-04-14'),

('DjangoCon Europe 2026', 'Conferinta europeana de programare Django/Python pentru tineri developeri. Talk-uri tehnice, sprint-uri de cod, networking cu programatori din 30+ tari. Burse de participare disponibile pentru studenti.', 'evenimente', 'DjangoCon Europe', 'Timisoara sau Cluj (locatie TBA)', 'Toamna 2026', NULL, '16+ ani', ARRAY['programare', 'Python', 'tech', 'conferinta'], false, 'Early bird de la 50 EUR', 'https://djangocon.eu/', 'djangocon.eu', 'mediu', 'approved', '2026-04-14'),

('Maker Faire Bucharest 2026', 'Festival de inventatori, creatori si inovatori. Expune-ti proiectul sau exploreaza roboti, drone, imprimante 3D, electronica si proiecte DIY. Sectiune speciala pentru tineri makeri.', 'evenimente', 'Maker Faire Romania', 'Bucuresti', 'Octombrie 2026', NULL, '10+ ani', ARRAY['maker', 'inventii', 'DIY', 'robotica'], false, 'Bilete de la 20 lei', 'https://makerfaire.ro/', 'makerfaire.ro', 'ușor', 'approved', '2026-04-14'),

('Festivalul Strada de C-Arte 2026', 'Festival de arte performative pentru copii si tineri, organizat in Bucuresti. Spectacole de teatru de strada, ateliere creative, muzica si dans. 100% gratuit si in aer liber.', 'evenimente', 'Asociatia Strada de C-Arte', 'Bucuresti (Parcul Izvor)', 'Iunie 2026', NULL, '6+ ani', ARRAY['arta', 'teatru', 'muzica', 'festival'], true, NULL, 'https://www.facebook.com/stradacarte/', 'stradacarte.ro', 'ușor', 'approved', '2026-04-14'),

('Gala Tinerilor Voluntari -- Premii Nationale 2026', 'Gala anuala care premiaza cele mai remarcabile initiative de voluntariat ale tinerilor din Romania. Nominalizari deschise in 6 categorii. Organizata de Pro Vobis.', 'evenimente', 'Pro Vobis -- Centrul National de Resurse pentru Voluntariat', 'Bucuresti', 'Decembrie 2026', '1 Noiembrie 2026', '14-30 ani', ARRAY['premii', 'gala', 'voluntariat', 'recunoastere'], true, NULL, 'https://www.provobis.ro/', 'provobis.ro', 'ușor', 'approved', '2026-04-14'),

('EU Debates -- Tineri pentru Europa', 'Serie de dezbateri organizate in universitati din Romania pe teme europene: mobilitate, democratie digitala, schimbari climatice, piata muncii. Format Oxford, premii pentru cei mai buni oratori.', 'evenimente', 'Eurodesk Romania / ANPCDEFP', 'Universitati din Romania', 'An scolar 2026-2027', NULL, '16-30 ani', ARRAY['debate', 'Europa', 'cetatenie', 'universitate'], true, NULL, 'https://www.eurodesk.ro/', 'eurodesk.ro', 'mediu', 'approved', '2026-04-14'),

-- === WORKSHOPURI NOI (8) ===
('Digital Kids -- Ateliere de Programare pentru Copii', 'Ateliere interactive de Scratch, Python si robotica pentru copii 7-14 ani. Invatare prin proiecte practice, jocuri si animatii. Prima lectie gratuita. Centre in Bucuresti, Cluj, Iasi.', 'workshopuri', 'Digital Kids Romania', 'Bucuresti, Cluj, Iasi + Online', 'Program continuu -- sesiuni saptamanale', NULL, '7-14 ani', ARRAY['programare', 'Scratch', 'robotica', 'copii'], false, 'De la 100 lei/luna', 'https://digitalkids.ro/', 'digitalkids.ro', 'ușor', 'approved', '2026-04-14'),

('Generation YES -- Educatie Antreprenoriala pentru Licee', 'Programul Generatia DA dezvolta competente antreprenoriale la liceeni. Workshop-uri de design thinking, marketing, pitch si management de proiect. Parteneri: universități din Romania.', 'workshopuri', 'Asociatia Generatia DA', 'National (licee partenere)', 'An scolar 2026-2027', NULL, '15-19 ani', ARRAY['antreprenoriat', 'design thinking', 'liceu', 'business'], true, NULL, 'https://generatiada.ro/', 'generatiada.ro', 'mediu', 'approved', '2026-04-14'),

('SALTO-YOUTH -- Training: Digital Tools for Youth Work', 'Training Erasmus+ de 5 zile pe instrumente digitale in lucrul cu tinerii. Aplicatii, platforme colaborative, gamificare si storytelling digital. Transport si cazare acoperite de UE.', 'workshopuri', 'SALTO-YOUTH / Erasmus+', 'Spania (Barcelona)', '10-14 Noiembrie 2026', '1 Octombrie 2026', '18-30 ani', ARRAY['digital', 'Erasmus+', 'youth work', 'international'], true, NULL, 'https://salto-youth.net/tools/european-training-calendar/', 'salto-youth.net', 'mediu', 'approved', '2026-04-14'),

('Scoala de Valori -- Workshop-uri de Public Speaking', 'Cursuri de public speaking, comunicare si leadership pentru tineri. Format interactiv cu exercitii practice, filmare video si feedback personalizat. Disponibil in 5 orase.', 'workshopuri', 'Scoala de Valori', 'Bucuresti, Cluj, Timisoara, Iasi, Brasov', 'Sesiuni lunare', NULL, '14-25 ani', ARRAY['public speaking', 'comunicare', 'leadership', 'dezvoltare'], false, 'De la 150 lei/curs', 'https://www.scoaladevalori.ro/', 'scoaladevalori.ro', 'mediu', 'approved', '2026-04-14'),

('Asociatia Techsoup -- Digital Skills for NGOs', 'Workshop-uri gratuite de competente digitale pentru voluntarii si angajatii ONG-urilor. Google Workspace, social media, cybersecurity, fundraising online si data analytics.', 'workshopuri', 'TechSoup Romania', 'Online (Zoom)', 'Sesiuni lunare', NULL, '18+ ani', ARRAY['digital', 'ONG', 'Google', 'fundraising'], true, NULL, 'https://www.techsoup.ro/', 'techsoup.ro', 'ușor', 'approved', '2026-04-14'),

('Goethe-Institut Bukarest -- Deutsch fur Jugendliche', 'Cursuri gratuite de limba germana pentru tineri, organizate de Goethe-Institut Bucuresti. Activitati culturale, film, muzica si proiecte creative in limba germana. Certificate recunoscute international.', 'workshopuri', 'Goethe-Institut Bukarest', 'Bucuresti + Online', 'An scolar 2026-2027', NULL, '14-18 ani', ARRAY['limba germana', 'cultura', 'certificat', 'international'], true, NULL, 'https://www.goethe.de/ins/ro/ro/index.html', 'goethe.de', 'ușor', 'approved', '2026-04-14'),

('Institut Francais -- Ateliere de Limba Franceza pentru Tineri', 'Institutul Francez din Romania ofera ateliere culturale si lingvistice pentru tineri. Teatru in franceza, cinecluburi, dezbateri si proiecte artistice. Certificari DELF/DALF disponibile.', 'workshopuri', 'Institut Francais de Roumanie', 'Bucuresti, Cluj, Timisoara, Iasi', 'Program continuu', NULL, '14-25 ani', ARRAY['limba franceza', 'cultura', 'teatru', 'certificat'], false, 'De la 50 lei/atelier', 'https://www.institutfrancais.ro/', 'institutfrancais.ro', 'ușor', 'approved', '2026-04-14'),

('British Council Romania -- IELTS Prep & Skills Workshops', 'Workshop-uri de pregatire IELTS si dezvoltare a competentelor de limba engleza, organizate de British Council. Focus pe academic writing, speaking si critical thinking. Reduceri pentru elevi si studenti.', 'workshopuri', 'British Council Romania', 'Bucuresti + Online', 'Program continuu', NULL, '16+ ani', ARRAY['engleza', 'IELTS', 'academic', 'certificat'], false, 'De la 200 lei', 'https://www.britishcouncil.ro/', 'britishcouncil.ro', 'mediu', 'approved', '2026-04-14'),

-- === COMPETITII NOI (7) ===
('Olimpiada de Limba Engleza 2026', 'Olimpiada nationala de limba engleza, organizata de Ministerul Educatiei. Etape judetene si nationala. Subiecte de reading, writing, listening si use of English. Calificari la competitii internationale.', 'competitii', 'Ministerul Educatiei', 'National', 'Martie - Mai 2026', NULL, '14-19 ani', ARRAY['engleza', 'olimpiada', 'limbi straine', 'concurs'], true, NULL, 'https://edu.ro', 'edu.ro', 'avansat', 'approved', '2026-04-14'),

('Debate Academy Romania -- Campionatul National 2026', 'Campionatul national de debate in format World Schools. Echipe de 3 elevi argumenteaza pe teme de actualitate in limba engleza sau romana. Calificari pentru Campionatul European si Mondial.', 'competitii', 'Debate Academy Romania', 'Finala la Bucuresti', 'Aprilie - Iunie 2026', NULL, '14-19 ani', ARRAY['debate', 'oratorie', 'gandire critica', 'engleza'], true, NULL, 'https://debateacademy.ro/', 'debateacademy.ro', 'avansat', 'approved', '2026-04-14'),

('NASA Space Apps Challenge Romania 2026', 'Hackathon global organizat de NASA, cu hub la Bucuresti. Echipe rezolva provocari reale legate de explorarea spatiala folosind date deschise NASA. 48 de ore de inovatie si creativitate.', 'competitii', 'NASA / Local Hub Romania', 'Bucuresti + Online', 'Octombrie 2026', NULL, '14+ ani', ARRAY['spatiu', 'NASA', 'hackathon', 'date deschise'], true, NULL, 'https://www.spaceappschallenge.org/', 'spaceappschallenge.org', 'avansat', 'approved', '2026-04-14'),

('Google Code Jam 2026 -- Participare din Romania', 'Competitie globala de programare organizata de Google. Runde online, probleme algoritmice crescande in dificultate. Premii de 15000 USD. Multi romani in top 100 mondial anual.', 'competitii', 'Google', 'Online (global)', 'Martie - August 2026', NULL, '16+ ani', ARRAY['programare', 'algoritmi', 'Google', 'global'], true, NULL, 'https://codingcompetitions.withgoogle.com/', 'google.com', 'avansat', 'approved', '2026-04-14'),

('Concursul National de Dezbateri ARDOR 2026', 'Asociatia Romana de Dezbateri, Oratorie si Retorica organizeaza campionatul national pentru liceeni. Format Karl Popper si Lincoln-Douglas. Dezvolta gandire critica si abilitati de prezentare.', 'competitii', 'ARDOR', 'National -> Finala la Bucuresti', 'An scolar 2026', NULL, '14-19 ani', ARRAY['debate', 'oratorie', 'retorica', 'gandire critica'], true, NULL, 'https://www.ardor.org.ro/', 'ardor.org.ro', 'mediu', 'approved', '2026-04-14'),

('Romanian Master of Mathematics 2026', 'Competitie internationala de matematica de elita organizata la Bucuresti. Participanti din 20+ tari. Probleme la nivel de Olimpiada Internationala de Matematica. Romania -- tara gazda.', 'competitii', 'Ministerul Educatiei / SSMR', 'Bucuresti', 'Februarie 2026', NULL, '15-19 ani', ARRAY['matematica', 'international', 'elita', 'Bucuresti'], true, NULL, 'https://rmms.lbi.ro/', 'rmms.lbi.ro', 'avansat', 'approved', '2026-04-14'),

('Concursul European de Stiinta EUCYS -- Selectia Romania', 'EU Contest for Young Scientists -- selectia nationala. Proiecte originale de cercetare in stiinte exacte, inginerie, informatica, biologie. Castigatorii reprezinta Romania la finala europeana.', 'competitii', 'Ministerul Educatiei / Comisia Europeana', 'National -> Finala europeana', '2026 -- inscrieri din ianuarie', NULL, '14-21 ani', ARRAY['stiinta', 'cercetare', 'EU', 'proiect'], true, NULL, 'https://eucys.eu/', 'eucys.eu', 'avansat', 'approved', '2026-04-14'),

-- === TABERE NOI (5) ===
('Tabara de Informatica -- Grigore Moisil 2026', 'Tabara nationala de informatica pentru pasionati de programare si algoritmi. Pregatire intensiva cu profesori de lot olimpic, concursuri zilnice si activitati recreative. Muntii Bucegi.', 'tabere', 'Societatea de Stiinte Matematice din Romania', 'Sinaia, Prahova', 'Iulie 2026', '15 Iunie 2026', '14-19 ani', ARRAY['informatica', 'programare', 'tabara', 'olimpiada'], false, 'Contributie 800 lei', 'https://www.ssmr.ro/', 'ssmr.ro', 'avansat', 'approved', '2026-04-14'),

('Tabara Verde -- Educatie Ecologica in Arii Protejate', 'Tabara dedicata educatiei ecologice in Parcul National Retezat. Drumetii montane, studiu flora-fauna, GPS geocaching, ateliere de reciclare creativa. Cazare in cabane montane.', 'tabere', 'Administratia Parcului National Retezat', 'Parcul National Retezat', 'August 2026', '1 Iulie 2026', '14-18 ani', ARRAY['ecologie', 'drumetie', 'natura', 'parc national'], false, 'Contributie 600 lei', 'https://www.retezat.ro/', 'retezat.ro', 'mediu', 'approved', '2026-04-14'),

('Tabara de Teatru si Improvizatie -- Sibiu 2026', 'Tabara de vara axata pe teatru, improvizatie si exprimare artistica. Workshop-uri sustinute de actori profesionisti din Festivalul International de Teatru de la Sibiu. Spectacol final in aer liber.', 'tabere', 'Asociatia Culturala Artelier', 'Sibiu', 'Iulie 2026', '20 Iunie 2026', '14-22 ani', ARRAY['teatru', 'improvizatie', 'arta', 'festival'], false, 'Contributie 700 lei', 'https://www.sibfest.ro/', 'artelier.ro', 'ușor', 'approved', '2026-04-14'),

('Tabara de Limba Engleza -- English Summer Camp Sinaia', 'Tabara de engleza cu profesori nativi, activitati sportive si culturale. Testare si grupare pe nivele, activitati outdoor, seri tematice. Certificat de participare Cambridge.', 'tabere', 'Language Link Romania', 'Sinaia, Prahova', 'Iulie-August 2026', '15 Iunie 2026', '10-17 ani', ARRAY['engleza', 'tabara de vara', 'Cambridge', 'sport'], false, 'De la 1500 lei/saptamana', 'https://www.languagelink.ro/', 'languagelink.ro', 'ușor', 'approved', '2026-04-14'),

('Tabara de Robotica si STEM -- RoboTech Camp 2026', 'Tabara de vara dedicata pasionatilor de robotica, electronica si programare. Construiesti roboti Arduino, printezi 3D, programezi drone si participi la mini-competitii. Echipament inclus.', 'tabere', 'RoboTech Romania', 'Predeal, Brasov', 'August 2026', '10 Iulie 2026', '12-18 ani', ARRAY['robotica', 'STEM', 'Arduino', 'programare'], false, 'Contributie 1200 lei', 'https://www.robotech.ro/', 'robotech.ro', 'mediu', 'approved', '2026-04-14'),

-- === BURSE NOI (5) ===
('Fulbright Romania -- Burse pentru Studii in SUA', 'Programul Fulbright ofera burse complete pentru studii de master si doctorat in Statele Unite. Acoperire totala: taxe scolare, asigurare, bilet de avion, bani de trai. Termen: toamna 2026.', 'burse', 'Comisia Fulbright Romania', 'SUA (universitati americane)', 'Inscrieri toamna 2026 pentru 2027-2028', 'Octombrie 2026', '22-35 ani', ARRAY['bursa', 'SUA', 'master', 'doctorat'], true, NULL, 'https://www.fulbright.ro/', 'fulbright.ro', 'avansat', 'approved', '2026-04-14'),

('Chevening Romania -- Burse Guvernul Britanic', 'Programul Chevening ofera burse pentru studii de master in Marea Britanie, finantate integral de guvernul britanic. Include taxe, cazare, bilet de avion si alocatie lunara.', 'burse', 'Ambasada Marii Britanii in Romania', 'Marea Britanie', 'Inscrieri 2026', 'Noiembrie 2026', '22-35 ani', ARRAY['bursa', 'UK', 'master', 'leadership'], true, NULL, 'https://www.chevening.org/', 'chevening.org', 'avansat', 'approved', '2026-04-14'),

('Erasmus Mundus -- Burse de Master Joint Degree', 'Erasmus Mundus finanteaza masterate internationale oferite de consorții de universitati din UE. Bursa include taxe, calatorii, asigurare si alocatie. Peste 160 de programe disponibile.', 'burse', 'Comisia Europeana / EACEA', 'Universitati din UE (consorții)', 'Inscrieri toamna 2026', NULL, '20-30 ani', ARRAY['Erasmus Mundus', 'master', 'international', 'UE'], true, NULL, 'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en', 'ec.europa.eu', 'avansat', 'approved', '2026-04-14'),

('Bursa Theodor Pallady -- Arte Vizuale pentru Tineri Artisti', 'Bursa acordata anual de Ministerul Culturii pentru tineri artisti plastici. Finantare pentru proiecte de creatie, expozitii si rezidente artistice. Portofoliu necesar la inscriere.', 'burse', 'Ministerul Culturii', 'Romania', 'Inscrieri primavara 2026', 'Mai 2026', '18-35 ani', ARRAY['arta', 'bursa', 'cultura', 'creatie'], true, NULL, 'https://www.culturadata.ro/', 'culturadata.ro', 'avansat', 'approved', '2026-04-14'),

('DAAD Romania -- Burse pentru Studii in Germania', 'DAAD (Serviciul German de Schimb Academic) ofera burse pentru studii, cercetare si stagii in Germania. Programe de vara, master si doctorat. Peste 100 de tipuri de burse disponibile.', 'burse', 'DAAD -- Serviciul German de Schimb Academic', 'Germania', 'Inscrieri pe parcursul anului', NULL, '18-35 ani', ARRAY['bursa', 'Germania', 'studii', 'cercetare'], true, NULL, 'https://www.daad.ro/', 'daad.ro', 'mediu', 'approved', '2026-04-14');
